### ISSUE TITLE
OnNewTradeOffer not being called

### ISSUE THREAD

**Issue by redside100** [Jessecar96/SteamBot#1000]
Hey,

Whenever I send my bot a trade offer, my OnNewTradeOffer method isn't even being called. Only after I cancel my trade offer, this pops up in the log: `[Bot 2016-06-06 18:25:20] INFO: Trade offer 1301551875 failed
`

Any help is appreciated. :)

**Comment by BlueRaja** [comment]
Are you using the latest version?  I thought this was fixed a few weeks ago.

**Comment by redside100** [comment]
Never mind, I found out I was using an outdated version of the bot.
