### ISSUE TITLE
Error Newtonsoft.Json.JsonReaderException

### ISSUE THREAD

**Issue by PiskyM8** [Jessecar96/SteamBot#1001]
When I run the Steam bot with all the correct account information and nothing seems to be wrong i get this error- "An exception of type 'Newtonsoft.Json.JsonReaderException' occurred in Newtonsoft.Json.dll but was not handled in user code

Additional information: After parsing a value an unexpected character was encountered: A. Path 'Admins[0]', line 3, position 1."

Any help would be appreciated.

**Comment by scholtzm** [comment]
#427 #527

**Comment by PiskyM8** [comment]
Thanks
