### ISSUE TITLE
 Failed to generate 2FA code. Make sure you have linked the authenticator via SteamBot.

### ISSUE THREAD

**Issue by minecraftinventz** [Jessecar96/SteamBot#1003]
[Bot #1 2016-06-17 17:36:23] ERROR: Login Error: AccountLogonDeniedNeedTwoFactorCode
[Bot #1 2016-06-17 17:36:24] ERROR: Failed to generate 2FA code. Make sure you have linked the authenticator via SteamBot.

I get these two errors despite having the ma files and sentry files in place. I've tried doing exec 0 linkauth but it gives me an error saying that it can't get it.

Why is this?

**Comment by scholtzm** [comment]
> it gives me an error saying that it can't get it

That's a bit vague, don't you think?

**Comment by minecraftinventz** [comment]
ERROR: Mobile authenticator has already been linked!

**Comment by minecraftinventz** [comment]
Anyone?

**Comment by waylaidwanderer** [comment]
Make sure the authfile is properly named, i.e. `username.auth` and not `steamid.auth`, and that it's in the `authfiles` folder.

**Comment by minecraftinventz** [comment]
It's the exact same name as the login which is the username and it's in the authfiles folder.

**Comment by waylaidwanderer** [comment]
Make sure you've put it in the correct folder. There's `Bin/Debug` and `Bin/Release`.

**Comment by minecraftinventz** [comment]
I have done this correctly.

**Comment by minecraftinventz** [comment]
Hello anyone?

**Comment by Gicminos** [comment]
Same problem

**Comment by Gicminos** [comment]
I've checked the maFile before and after decript Steam Desktop Authenticator, it's the same.

**Comment by toomi17** [comment]
You need to Unlink all your things related to escrow from your bot account. (Cell phone, Guard via mail and mob guard) And link again but on your bot manager. Maybe there ir a better sol but this worked for me.  Good luck
