### ISSUE TITLE
Trade Offer Acception not working

### ISSUE THREAD

**Issue by levithanmaou** [Jessecar96/SteamBot#1005]
Hello,

I have read through all the source code and compiled it.

However the Bot will not accept the Tradeoffers:

I am using public override void OnTradeOfferUpdated(TradeOffer offer) in a custom CustomUserHandler.cs

offer.Accept() will not work and also Bot.AcceptAllMobileTradeConfirmations() doesnt work.

Please help me with this issue.

Thanks in advance,

Leviathan-Maou

**Comment by BlueRaja** [comment]
Please debug it to ensure it's a bug with the library and not your UserHandler - see #427 and #527
