### ISSUE TITLE
Accepted trade offer has no items in it

### ISSUE THREAD

**Issue by checkerschaf** [Jessecar96/SteamBot#1014]
Hey, I wrote a bot to send trade offers to users. After successfully sending my offer I get a OnTradeOfferUpdated() call with correct data, but when I get the OnTradeOfferUpdated() call after I accepted the offer (userside, not botside), offer.Items.GetTheirItems() is empty. I have no idea why.. 

Log: 
BEFORE ACCEPTION: DEBUG: Trade offer update - id: 1234, items: 0-1, status: TradeOfferStateActive
AFTER: DEBUG: Trade offer update - id: 1234, items: 0-0, status: TradeOfferStateAccepted
items is (my)-(his)

Thanks for your help :)

Note: steamstat.us shows no errors, also checked it over 3 days

**Comment by fjch1997** [comment]
I have the similar issues with trade offers but i think it's something internally in steam servers. Sometimes it can generate blank offer (It's not that SteamTrade got the offer content wrong). When you go to pending trade offers page in a web browser, it's still blank.

**Comment by checkerschaf** [comment]
Strange, for me it's working in browser, but TradeOfferStateAccepted has no Items in it: https://vgy.me/clQkkA.png How can I get the new items anyway?

**Comment by fjch1997** [comment]
Then my case is different from that of yours
:)

**Comment by checkerschaf** [comment]
Mhh. How you get item details after a trade (offer)?

**Comment by fjch1997** [comment]
If it's a trade, i don't believe you can achieve this in this library. You may go to the user's trade history page and parse the content.
If it's a trade offer and you have a trade offer ID, initialize an instance of TradeOfferWebAPI and call TradeOfferWebAPI.GetTradeOffer(string). If you don't have a ID, call TradeOfferWebAPI.GetTradeOffers(bool getSentOffers, bool getReceivedOffers, bool getDescriptions, bool activeOnly, bool historicalOnly, string timeHistoricalCutoff = "1389106496", string language = "en_us")

**Comment by checkerschaf** [comment]
Are the assetids of TradeOfferWebAPI.GetTradeOffer(string) already updated?

**Comment by scholtzm** [comment]
Updated with what information? Items attached to trade offer will never change their properties.

**Comment by checkerschaf** [comment]
Wrong! Assetid (and I think instanceid etc too) changes after a trade!

**Comment by scholtzm** [comment]
> Items attached to trade offer will never change their properties.

I know that and my statement does not contradict yours. The list of items attached to trade offer will not change.

**Comment by checkerschaf** [comment]
Ah ok, sure :P

**Comment by sy1989** [comment]
i think "your inventory is private" make id change after a trade!

**Comment by fjch1997** [comment]
@sy1989 according to my testing assetid is bound to change after a successful trade.

**Comment by L4rsS** [comment]
Yes, the AssetIDs of the items change after each trade! Does anyone know how to get this new ids? I only have access to the old ones. I heard it's stored in the trade receipt or sth

**Comment by fjch1997** [comment]
@L4rsS Unfortunately, I have checked a lot of places and there is no way to get the new ids.

**Comment by L4rsS** [comment]
@fjch1997 Seriously not possible?
