### ISSUE TITLE
Wall of ERROR

### ISSUE THREAD

**Issue by Minoryop** [Jessecar96/SteamBot#1026]
Shortly after I was able to run my bot I was introduced to this dreaded wall of text
![capture](https://cloud.githubusercontent.com/assets/18340446/16542612/40d2b6a4-4064-11e6-8db6-eb4388965ab8.PNG)
after I got this I stopped the bot and started again, receiving a different wall of text.
![capture 2](https://cloud.githubusercontent.com/assets/18340446/16542627/e5dba02a-4064-11e6-99f0-f02826db8478.PNG)

**Comment by scholtzm** [comment]
You might want to setup your bot properly, e.g. your API key in `settings.json`.

**Comment by Minoryop** [comment]
Thanks really helped! :D
