### ISSUE TITLE
User Handler Instantiated Multiple Times

### ISSUE THREAD

**Issue by wilson208** [Jessecar96/SteamBot#1028]
Hi All,

I have created a user handler and within the instantiation of the class, I set some class variables (Caching some content from DB). I am running with a single bot. However, for the single bot the UserHandler is being instantiated as many as 10 times upon startup of the bot. 

Is this normal behaviour? If so, is there any way of being able to cache data across every re-instantiation of the UserHandler?

Thanks in advance and all help is much appreciated!

Wilson.

**Comment by RafalNiewinski** [comment]
Yes, it is normal behaviour. UserHandler is instantiated for all ```UserHandler``` interface events separately. 

For example when 2 users sends trade offer to our bot, first one is processed be single instance of configured ```UserHandler``` and second will be processed by another instance.

If you want to store whatever  data persistently you should store it... for example in the ```Bot``` class which is instantiated per configured bot. So if you use this example and has configured 3 bots in ```settings.json``` each bot should have separated data.
