### ISSUE TITLE
When I start the bot and auth it I get this error

### ISSUE THREAD

**Issue by Deathrider1026** [Jessecar96/SteamBot#1034]
When I run it. It logs me in and I get auto authed. Then for some reason I get a huge [red error](https://gyazo.com/845e5c729c16384f11382867e35a27f9)
Also when I do "start 0" or I say start then then username of the steam account (The login username) I don't see my bot go online, it stays offline on steam. That is supposed to start the bot right? I need help with both of these things. Any help? Thank you!

**Comment by SlimyOp** [comment]
Same :(

**Comment by Deathrider1026** [comment]
@SlimyOp 
To fix it I went to change my steam api key thing and changed it in the json file. Then I started the sln and started it then waited 1 hour and close then start it again and it should work lol
