### ISSUE TITLE
Offline Trade Offer

### ISSUE THREAD

**Issue by Gicminos** [Jessecar96/SteamBot#1035]
I founded in the SteamBot the commands for a live trade offer, when other users send you an offer request. But how can I manage the offline trade offer? When user send you offer with tradeurl for example.

This isn't a very Issue, but I don't know where to ask my question.

Have a nice day,
Gicminos

**Comment by RafalNiewinski** [comment]
#427 #527

You can test this example user handler: https://github.com/Jessecar96/SteamBot/blob/master/SteamBot/TradeOfferUserHandler.cs

**Comment by Gicminos** [comment]
Okay, thanks and sorry for my question posted here.
