### ISSUE TITLE
Steam Bot problem

### ISSUE THREAD

**Issue by Marxstil** [Jessecar96/SteamBot#1040]
c:\Users\MarxstilPC\Desktop\SteamTrade\SteamWeb.cs:line 85
c:\Users\MarxstilPC\Desktop\SteamTrade\SteamWeb.cs:line 26
c:\Users\MarxstilPC\Desktop\SteamTrade\Inventory.cs:line 21
c:\Users\MarxstilPC\Desktop\SteamBot\Bot.cs:line 805
c:\Users\MarxstilPC\Desktop\SteamBot\Bot.cs:line 111
c:\Users\MarxstilPC\Desktop\SteamBot\Bot.cs:line 998
c:\Users\MarxstilPC\Desktop\SteamBot\ItemGivingUserHandler.cs:line 66
c:\Users\MarxstilPC\Desktop\SteamBot\Bot.cs:line 435
c:\Users\MarxstilPC\Desktop\SteamBot\Bot.cs:line 415
c:\Users\MarxstilPC\Desktop\SteamBot\Bot.cs:line 895

How fix with my bot (red error) ?
 Thank you!

**Comment by FrozenHaxor** [comment]
Lol.

**Comment by BlueRaja** [comment]
#427 #527
