### ISSUE TITLE
Trade problem

### ISSUE THREAD

**Issue by Danielix99** [Jessecar96/SteamBot#1041]
I dont know very good the cs language but reading the code i've discovered that the bot have the possibility to trade only scrap metal refined and the reclaimed metal....but if i start the live trade and add some of this metal, the trade doesn't show the item added and i cannot accept the trade. obiuvsly if i add some other items, when i press accept, it crash because i haven't programmed the item in the code.

**Comment by BlueRaja** [comment]
#427 #527

**Comment by Danielix99** [comment]
first of all i know programming, but i know java javascript php c++ asmx64 but i dont know the c# and i have no time to let know it, second thanks for the answer, i go on s.o.
