### ISSUE TITLE
Can't login to bot account

### ISSUE THREAD

**Issue by x3reunion** [Jessecar96/SteamBot#1043]
Hello. First of all i want to tell You guys that I am green with this. I am just a beginner that wants to set up a key bot for TF2. SteamBot can't login me at the start. I am getting all the time Error Failed to logrythein : 85
Also getting all the time WARN: Disconnected from Steam network.

Can someone explain me what is wrong? I have right setted up everything in settings.json file.

Please reply ASAP :) Greeting Jacob

**Comment by scholtzm** [comment]
#427 #527
