### ISSUE TITLE
Wont connect to steam?

### ISSUE THREAD

**Issue by Antzaa** [Jessecar96/SteamBot#1067]
[(System) 2017-03-01 00.09.31] INFO: Launching Bot Tradebot...
[Tradebot 2017-03-01 00.09.31] SUCCESS: Done Loading Bot!
Type help for bot manager commands.
botmgr > botmgr >
and nothing happenings.

**Comment by BlueRaja** [comment]
https://github.com/Jessecar96/SteamBot/wiki/Usage-Guide
Also #427

**Comment by waylaidwanderer** [comment]
https://github.com/Jessecar96/SteamBot/wiki/Configuration-Guide#full-customization-with-userhandlers

Probably link this instead next time.
