### ISSUE TITLE
.Net Core and Newtonsoft.Json

### ISSUE THREAD

**Issue by msollicito** [Jessecar96/SteamBot#1073]
I have installed the .Net Core version of Newtonsoft.Json - like this
Install-Package CoreCompat.Newtonsoft.Json -Pre
However it still says it cannot find a lot of the stuff I would expect it to find - like JsonPropertyAttribute
and JsonProperty 

Any idea why?

**Comment by aleksasteam** [comment]
SteamBot works on .Net Framework, no one ported it to .Net Core.

Why don't you do a package restore? It will pull the correct packages.

**Comment by scholtzm** [comment]
SteamKit currently does not even support .NET Core. Should be available in 2.0 though.
