### ISSUE TITLE
I have a problem 

### ISSUE THREAD

**Issue by Deathzz007** [Jessecar96/SteamBot#1077]
![report](https://cloud.githubusercontent.com/assets/28906045/26378754/d013cd92-3fca-11e7-9df6-40032008cf38.PNG)

It keeps going into a loop and until it says InvalidPassword. I tried restarting the bot, and also tried finding the shared_secret and identity_secret but couldn't find it.

Please help me so I can make a a bot. Thank you

**Comment by BlueRaja** [comment]
#427
