### ISSUE TITLE
Emm,There is a people in zhihu.com Plagiarisming Your Code

### ISSUE THREAD

**Issue by SakuraLove** [Jessecar96/SteamBot#1081]
The Link is here : https://zhuanlan.zhihu.com/p/27169225
I hope you can know this and stop what he is dong.

**Comment by BlueRaja** [comment]
That appears to be for SDA, not SteamBot?

In either case, they're both open-source, with permissive licenses, so people are free to "plagiarize" however they want.

**Comment by SakuraLove** [comment]
emm,that is my wrong.I post a wrong website address.
You can check this out
https://zhuanlan.zhihu.com/p/27469083

**Comment by SakuraLove** [comment]
and the he said "然后下载我这边开发的bot程序，下载链接如下：https://pan.baidu.com/s/1geHiblD"
If you use the translation,you will know that he is saying that he progrem this code.

**Comment by SakuraLove** [comment]
And you can check out that is he one of the developer.
