### ISSUE TITLE
emm,there is a person in zhihu.com Plagiarisming Your Code

### ISSUE THREAD

**Issue by SakuraLove** [Jessecar96/SteamBot#1082]
emm,that is my wrong.I post a wrong website address in another issue.
But You can check this out again,
https://zhuanlan.zhihu.com/p/27469083
and the he said "然后下载我这边开发的bot程序，下载链接如下：https://pan.baidu.com/s/1geHiblD"
If you use the translation,you will know that he is saying that he progrem this code.
And you can check out that is he one of the developer.
Just check that :D

**Comment by SakuraLove** [comment]
And by the way,i contact with him,and he sell the code for more than ten thousand Chinese YUAN

**Comment by SlothGod** [comment]
The code is free to the public to redistribute at their own free will as mentioned [here](https://github.com/Jessecar96/SteamBot/blob/master/LICENSE)
