### ISSUE TITLE
2 minutes to start a Bot

### ISSUE THREAD

**Issue by bgabraga2** [Jessecar96/SteamBot#1083]
Is it happening to you too, about 2 minutes to start a bot? I used to use an old Bot (BotControlClass), which I developed 1 year ago, and it took only a few seconds to connect. However, since I downloaded it again to re-develop, it is like this, taking too long to connect. Can someone help me? Is it anyway or do you have any settings that I can optimize this?
![bot](https://user-images.githubusercontent.com/25314209/29105858-4ea2f7e6-7ca7-11e7-90bc-fd7adce8f090.png)

**Comment by BlueRaja** [comment]
This should be fixed by https://github.com/Jessecar96/SteamBot/pull/1068.  However no one is actively maintaining this repo, so no one has merged it.

Please test it for a few days, and if it works alright, I'll merge it.

**Comment by bgabraga2** [comment]
Perfect! That worked, thank you!

**Comment by kilpkonn** [comment]
Can we close this issue as it has been fixed long time ago?
