### ISSUE TITLE
Few questions first time using this project.

### ISSUE THREAD

**Issue by tryzombie501** [Jessecar96/SteamBot#1085]
I like this project makes it very easy to communicate with steam however how would i implement a looped background thread in the example bot code? I would use it for things like updating a cache and or updating stuff every 5 hours for example. 

And how would i figure out what user messaged the bot via steam messaging?

Many thanks!

**Comment by scholtzm** [comment]
#427 #527

**Comment by tryzombie501** [comment]
My apologies.
