### ISSUE TITLE
ArgumentNullException at SteamGuardAccount.FetchConfirmations() in Bot.cs

### ISSUE THREAD

**Issue by OfficialSui** [Jessecar96/SteamBot#1087]
For some weird reason all of a sudden my bot seems to not be able to confirm any open mobile confirmations. This seems to be the source of the problem, but i have no clue how to fix it:

```
foreach (var confirmation in SteamGuardAccount.FetchConfirmations())
{
       if (SteamGuardAccount.AcceptConfirmation(confirmation))
       {
               Log.Success("Confirmed {0}. (Confirmation ID #{1})", confirmation.ConfirmationDescription, confirmation.ConfirmationID);
       }
}
```

**Comment by TimoKruth** [comment]
@OfficialSui is this still an issue? If yes I would love to try to help you.
If not please close this issue.

**Comment by OfficialSui** [comment]
@TimoKruth dont know if its still an open issue, it isnt an open issue for me anymore though so im closing.

**Comment by TimoKruth** [comment]
@OfficialSui As I am using SteamBot without any problem in that kind of way I guess it is perfect that you closed this issue.
Thank you very much for that fast reply :)
