### ISSUE TITLE
Handler is started 8-9 times on launch

### ISSUE THREAD

**Issue by CaptainJackas** [Jessecar96/SteamBot#1090]
When launching just the default bot with the default SimpleUserHandler.cs as handler, it seems that the handler is called 8-9 times on launch:
![name](https://user-images.githubusercontent.com/19432222/30588848-a4827900-9d38-11e7-99e1-3b95bb4536d6.png)
I used this code to for the output:
` public SimpleUserHandler (Bot bot, SteamID sid) : base(bot, sid) { Log.Success("started"); }`
Does anyone knows how to fix this?

**Comment by BlueRaja** [comment]
Intended behavior.  UserHandlers are created once for each user the bot interacts with.

Unfortunately UserHandlers are also often used for things that are not user-specific, by necessity.  That is not good design, but here we are.
