### ISSUE TITLE
Bot secure against fraud ?

### ISSUE THREAD

**Issue by F4ri0us** [Jessecar96/SteamBot#1091]
Hello,

I would like to know if your bot is secure against fraud when trading on CS GO items.
Let me explain: a few days ago I set up a trading bot CS GO developed in Node js with an external API that checked the prices of all items. I suffered a big fraud of several hundred euros with "jumping prices" on an article. The taken from this item was handled on the Steam market and instead of being sold at $ 0.50, it went up to $ 4.

1 / Is your bot able to detect "jumping prices" and manipulation of prices on the Steam market during an exchange? 
2 / Does your bot use the market price of Steam or an external API? 
3 / If a user wants to exchange with your bot 30 times the same article, is it possible to manage the overstock and limit the quantity of each item during a trading?

Thanks a lot for your answers.

**Comment by scholtzm** [comment]
You would have to code all of the features you mentioned yourself.

**Comment by BlueRaja** [comment]
This framework has no pricing features, you'll have to manage those yourself.  Also #427
