### ISSUE TITLE
one bot can just handle one trade  in a period?

### ISSUE THREAD

**Issue by stacklesshaha** [Jessecar96/SteamBot#1106]
![code](https://user-images.githubusercontent.com/35445580/34930681-a51dbaa8-fa05-11e7-9068-f4bd68070efe.png)
my english is not that good ,i hope someone can understand what i'm saying.this is my first request,if there is something wrong,forgive me. when i see that code ,i think it means  one bot can just handle one trade  in a period other than two or more . but i think one bot can handle two or more trade,can someone tell me why the code is written like that,is it because the steam restriction that one login user can just participate in one trade in a period?

**Comment by BlueRaja** [comment]
It's a Steam restriction.  You cannot have two trades open at a time.

**Comment by stacklesshaha** [comment]
thank you very much
