### ISSUE TITLE
Setting Trade Ratio

### ISSUE THREAD

**Issue by Bobby199777** [Jessecar96/SteamBot#1107]
Where do you set the personal trade ratio involved with the item trades, plus what items can they trade for the cards?

**Comment by BlueRaja** [comment]
This is just a library for writing your own bot.  There is no "trade ratio".

**Comment by Bobby199777** [comment]
so this isnt the bot its just random parts of code?

**Comment by BlueRaja** [comment]
#527 
Locking this thread - sorry, don't mean to be rude, but every time you post it emails dozens of people
