### ISSUE TITLE
[Virus Detect on Starting Bot] HackTool:MSIL/Stimilani.A

### ISSUE THREAD

**Issue by kyilintun2017** [Jessecar96/SteamBot#1155]
Error Show on  SpawnBotThread(BotConfig);
 Line 388 of BotManager.cs.

Could not load file or assembly 'SteamTrade, Version=0.1.0.25658, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation did not complete successfully because the file contains a virus or potentially unwanted software. (Exception from HRESULT: 0x800700E1)

**Comment by aleksamagicka** [comment]
Probably a false positive

**Comment by kyilintun2017** [comment]
For Visual Refernece. Please kindly advise.


![image](https://user-images.githubusercontent.com/26317504/67445563-ee20a480-f63f-11e9-9b39-5c23660bc375.png)

**Comment by aleksamagicka** [comment]
Just add the whole project folder to exclusions in your AV

**Comment by kyilintun2017** [comment]
ok thanks for the reply. I'll try.
