### ISSUE TITLE
What versions of vs?

### ISSUE THREAD

**Issue by WinterWolf2-0** [Jessecar96/SteamBot#1157]
What versions of vs 2010, and 2015 should i use? Thanks' to anyone who answers!

**Comment by X4nd2mm** [comment]
VS 2019 Community, works for me

**Comment by WinterWolf2-0** [comment]
> VS 2019 Community, works for me

Thanks, had this post up for a while now! One last thing, is this possibly outdated? The last commit was in around 2018, So thats why i asked.

**Comment by X4nd2mm** [comment]
I'm not sure. A few Things are buggy for me, but all in all it seems to work.
