### ISSUE TITLE
SteamTrade.dll is marked as a virus

### ISSUE THREAD

**Issue by fjch1997** [Jessecar96/SteamBot#1159]
The current code on master results in SteamTrade.dll being marked as a virus, unfortunately.

However, I was able to resolve this by simply moving all the code from `SteamTrade` to `ExampleBot`, and removing some unused classes.

**Comment by BlueRaja** [comment]
False positive: https://github.com/Jessecar96/SteamBot/issues?q=is%3Aissue+virus
