### ISSUE TITLE
SimpleUserHandler Help!

### ISSUE THREAD

**Issue by ghost** [Jessecar96/SteamBot#257]
Hey, I'm currently using the SteamBot and I want to import the SimpleUserHandler.cs Posted for scrapbanking [here](http://www.reddit.com/r/tf2trade/comments/19zvu2/psa_remember_when_i_released_the_source_code_for/) But when I put that in Steambot/SimpleUserHandler.cs and I launch the SteamBot.exe it runs fine but it doesn't load the Handler I loaded. All it can do is take scrap and when I try to put in items it just says There was an error in your trade. This is the whole chat:

```
[TradeBot] MBot: Success. Please put up your items. 18:03:32
You added The Loch-n-Load 18:03:35
You added The Candy Cane 18:03:36
You are ready 18:03:42
[TradeBot] MBot: There were errors in your trade: 18:03:43
[TradeBot] MBot: Item The Loch-n-Load is not a metal. 18:03:44
[TradeBot] MBot: Item The Candy Cane is not a metal. 18:03:45
[TradeBot] MBot: You must put up at least 1 scrap. 18:03:45
[TradeBot] MBot: Scrap: 0 18:03:46
```

This is my settings file(renamed **settings.json**):

``` JSON
{
"Admins":["234567"],
"ApiKey":"(api key)",
"mainLog": "syslog.log",
"UseSeparateProcesses": "false",
"Bots": [
        {
            "Username":"(Account Username)",
            "Password":"(Account Password)",
            "DisplayName":"MBot",
            "ChatResponse":"Welcome To MBot Trading Service!",
            "logFile": "MBot.log",
            "BotControlClass": "SteamBot.SimpleUserHandler",
            "MaximumTradeTime":300,
            "MaximumActionGap":30,
            "DisplayNamePrefix":"[TradeBot] ",
            "TradePollingInterval":800,
            "LogLevel":"Success"
        }
    ]
}
```

I would greatly appreciate the help for this if you can help me! Thanks!-Mgamer

**Comment by bennyd87708** [comment]
@lastofspades Hate to necro post, but how did you solve that OnLoginCompleted error? I have had it for a while now and have tried everything...

**Comment by scholtzm** [comment]
@bennyd87708 #427 & #527 
Also googling that error and clicking the first result works.
