### ISSUE TITLE
Steam Bot Dota 2 Exchange Keys to Rares, Rares to Keys

### ISSUE THREAD

**Issue by thurzton** [Jessecar96/SteamBot#525]
Hi guys having some trouble here, I almost done at my bots it accepts friend request and accept trades but the thing i cant think about is how i will set it up to dota 2 items. For example i the trader put rares then my bot will put key and when trader put key my bot will put rares. Please help me guys ,I'm sorry if i posted it wrong but i will appreciate if someone really helps.

**Comment by clearlydead** [comment]
How to apply dota 2 steam bot?please i really need the answer ASAP...
