### ISSUE TITLE
Posting here cause no one helped me on reddit thread...

### ISSUE THREAD

**Issue by WildCard65** [Jessecar96/SteamBot#563]
I posted on the reddit page of steambot for a workaround on how to compile the bot without nuget(running ubuntu here, can't get nuget, can't use a monodevelop extension of nuget I found with help of google(can't install a linux package required for it cause it's not in any repo added to my system).
OS: Ubuntu 13.10 64bit.

**Comment by Enissay** [comment]
Bump, the wiki says nothing about how to install with linux (debian)... I've installed mono, and now I have no idea how to install SteamBot :<

**Comment by ThereWasADream** [comment]
This is not a help forum, nor is anyone on the internet obligated to help you simply because you post in a help forum.

#427

**Comment by Enissay** [comment]
Yeah, well, this is somehow a request to complete the wiki hosted here on github...

Anyway, nvm :>
