### ISSUE TITLE
Steam few days ago has changed Privacy settings

### ISSUE THREAD

**Issue by alf01** [Jessecar96/SteamBot#639]
Steam few days ago has automaticly changed inventory privacy settings for all users to "friends only" from "public". Is there any possible option to avoid geting UserInvetory throug "http://api.steampowered.com/IEconItems_730/GetPlayerItems/v0001/?key=" 
when user adding item to trade ?
Or only one possible option is to ask users to change their iventory privacy settings?

**Comment by Jessecar96** [comment]
Closed, merging all the inv ones into #642
