### ISSUE TITLE
GenericInventory URLs always return 302 "Moved temporarily"

### ISSUE THREAD

**Issue by BlueRaja** [Jessecar96/SteamBot#641]
Not sure how long this has been going on, but the URLs to retrieve the inventory used by GenericInventory are returning "302: Moved Temporarily".

`HttpWebRequest` automatically redirects, so the bot still works; but, this increases the time to load each inventory, as well as the potential failure points.

**Comment by Jessecar96** [comment]
This isn't really necessary or needed.
