### ISSUE TITLE
Wiki is outdated

### ISSUE THREAD

**Issue by scholtzm** [Jessecar96/SteamBot#668]
Current version of wiki is outdated and does not contain information regarding trade offers, [new config options](https://github.com/Jessecar96/SteamBot/wiki/Configuration-Guide#configure-the-bot) etc.

It would be a good idea to update it, perhaps even make it editable by anyone.

What needs to be updated:

- [x] Configuration Guide
 - [x] Bot Configuration Array
 - [x] Full Customization With UserHandlers
- [x] Usage Guide
 - [x] Missing exec command
 - [x] Missing auth commands

**Comment by scholtzm** [comment]
Could the Wiki be made completely open?

**Comment by BlueRaja** [comment]
I like this idea.  @Jessecar96 is that possible?

**Comment by Jessecar96** [comment]
Honestly didn't even know it was locked.  Just made it open now.

**Comment by scholtzm** [comment]
I have updated the first post with info about what needs to be updated.

I have also updated "Bot Configuration Array" in "Configuration Guide".

**Comment by chopraaa** [comment]
The wiki documentation is ridiculously pathetic. If you want to encourage developer contribution and not a simple compile-and-run scenario by traders, you should start by documenting the bot source properly.

The wiki contains procedures for a simple clone, compile and run. That's why all the issues that get posted here are meaningless. Don't expect people to post their issues on reddit if you can't maintain a wiki.

**Comment by BlueRaja** [comment]
It is a wiki - you are welcome to contribute.  We are all volunteers here.

**Comment by chopraaa** [comment]
I *am* here to contribute. You may realise that without the wiki, for someone who's new to project, it's difficult to get around. As @scholtzm mentioned, the wiki has absolutely no information regarding as to what SteamBot goes about itself.

**Comment by scholtzm** [comment]
Did you miss the "We are all volunteers here" part?

**Comment by NoChanceSD** [comment]
On a kind of related note, why not give write access to more people?
SteamBot hasn't been merging pull requests or getting new commits for a while.
Don't take me wrong though, it's just a suggestion.

**Comment by scholtzm** [comment]
There are 2 major problems, form factor and testability. Larger changes will often make your code base incompatible with original code which makes the whole process very slow and tedious. I wouldn't say pull requests are ignored, there is just no one and nothing that would test them. The only thing that tests the code right now is the CI which does building and that's it. Giving people write access is not going to change this.

You could fork of course, but that only leaves you with the same issues and unmanagable code base.

**Comment by NoChanceSD** [comment]
In my opinion it's not very hard to update large changes, at least for my code merging and resolving conflicts doesn't take long.
What i meant was giving access to other people for merging pull requests like WildCard for example which seems pretty active. Or just give access to directly write commits as the current contributors might not have enough time or lost interest in SteamBot. (I'm sorry if this isn't the case at all, just what it seems to me)

**Comment by AleksaSavic3** [comment]
@NoChanceSD is right, no pull requests and commits in a while. I'll try to test some PRs if I have time.

+1 for WildCard

**Comment by BlueRaja** [comment]
+1 from me also for @WildCard65 and @scholtzm getting merge/etc. permissions, as long as they remember to wait for other people to test/code-review before merging their own code _(WildCard in particular has submitted several PRs that were not only untested, but didn't even compile)_.

@Jessecar96, what do you say?

**Comment by Bottswana** [comment]
I would agree. Along with you BlueRaja these are the most active
experienced people. They are the most likely candidates for merge
permissions.

**Comment by NoChanceSD** [comment]
I'm glad someone agrees, hopefully they are interested in the offer.

**Comment by WildCard65** [comment]
I'm alright with your rule @BlueRaja

**Comment by scholtzm** [comment]
@NoChanceSD @AleksaSavic3 Remember that you can also contribute by reviewing and commenting on said Pull Requests.

I see several opened PRs but almost no one bothers to check them out. Another problem is that large PRs are pretty much impossible to test and doing it by hand is just tedious. Breaking changes become a problem because there is no proper versioning. Which brings us back to form factor issues I mentioned in my previous comment - huge untestable monolith.

Personally, I don't think more people with merge rights are going to do much. @BlueRaja has been here the whole time, he is active and has merged several PRs.

Frankly, I don't have time to contribute code and I don't need the rights to do code reviews.

@BlueRaja Thank you for mentioning me. :+1:

**Comment by Bottswana** [comment]
@scholtzm makes a fair point. Review of PR's can take place without Merge permissions. It's not merge rights that are the issue, its us having time to review incoming PR's correctly.

**Comment by speed-str** [comment]
Also the userhandler examples link is broken. needs to be updated

**Comment by RafalNiewinski** [comment]
I updated "Usage Guide" just now.

**Comment by scholtzm** [comment]
LGTM, marking as done.

**Comment by scholtzm** [comment]
Wait @BlueRaja "Configuration Guide" is still outdated, or not? 😄

**Comment by BlueRaja** [comment]
Guess I should read the whole post first

**Comment by RafalNiewinski** [comment]
It is time for "Configuration Guide". Updated...

BTW: Boredom at work can be useful

**Comment by scholtzm** [comment]
Good job. This can be finally closed.
