### ISSUE TITLE
"Auth" Help

### ISSUE THREAD

**Issue by ImStayFrosty** [Jessecar96/SteamBot#678]
I Have Typed In The Console Window "Auth 0=[Steam_Key] And It Still Doesnt Work.
STEAM_KEY == Auth Code

I Can Provide Screenshot If Needed.
Console Response:
Disconected From Network
ERROR: InvalidLoginAuthCode
INTERFACE: The Given SteamGuard Code Was Invalid.
Try Again Using Auth Command

I Am Sure The Code Is Right So Please Help.
Thanks,
-Killa-

**Comment by romanzdan** [comment]
Hi,all, i have the same isue, will you help me pls?
