### ISSUE TITLE
Trade Offer Support for Multiple Bots

### ISSUE THREAD

**Issue by goprocn** [Jessecar96/SteamBot#686]
Hi,

I have faced 1 issue when setting up multiple bots(different steam usernames). Trade works though, trade offer only works for 1 bot which the API KEY is bound to. When trade offers are sent to other bots, OnNewTradeOffer() does not get fired.

I'm configuring it like this:
{
"Admins":[""],
"ApiKey":"",
"mainLog": "syslog.log",
"UseSeparateProcesses": "false",
"AutoStartAllBots": "true",
"Bots": [
        {
            Settings for Bot 1
        }
         .
         .
         .
        {
            Settings for Bot N
        }
    ]
}

Does anyone know how to configure a different ApiKey for each bot respectively? I'm not sure if that is supported.

Thanks!

**Comment by scholtzm** [comment]
[Yes, it's supported.](https://github.com/Jessecar96/SteamBot/blob/master/Bin/Debug/settings-template.json#L11)

**Comment by goprocn** [comment]
Thanks a lot! You're a life saver!

**Comment by goprocn** [comment]
solved by changing "UseSeparateProcesses": "false" to "UseSeparateProcesses": "true"

**Comment by Jessecar96** [comment]
This is not a help desk.

**Comment by BlueRaja** [comment]
I believe this is a valid bug, and was possibly fixed by https://github.com/Jessecar96/SteamBot/pull/616
