### ISSUE TITLE
Steam Group Invite

### ISSUE THREAD

**Issue by urvianoob** [Jessecar96/SteamBot#690]
Hello, I'm new to this trading bot thing, and I really need your help.

I am trying to find a method for the bot to invite you to a specific group right after you've completed a trade with them.

![screenshot_1](https://cloud.githubusercontent.com/assets/10472191/5690479/d753bcb8-9859-11e4-9922-edd371ab4437.png)

This is some code I found on the issues page, and I entered my steamgroup 64 id
However, "inviteUserToGroup" is not a valid command.

I continued looking all over the issues page, and every solution is different.

Please help me, I just want to help out my group and make a few trading bots.

**Comment by Jessecar96** [comment]
This is not a help desk.

**Comment by scholtzm** [comment]
Also #427 and #527
