### ISSUE TITLE
Capcha

### ISSUE THREAD

**Issue by doktokto** [Jessecar96/SteamBot#691]
One of my bots can't send offer because steam asking to write capcha. Bot write that all okay and offer sent. When I tried to send offer in browser it asked for capcha. I wrote it and offer sent, but steam asking it in each trade offer. Please, help

**Comment by FrozenHaxor** [comment]
I don't know what do you expect from us, this is a recent and a global problem with no solution so far.

**Comment by Jessecar96** [comment]
#689 This is not a help desk.
