### ISSUE TITLE
SteamBot crashes when you invite it to watch a game

### ISSUE THREAD

**Issue by BlueRaja** [Jessecar96/SteamBot#692]
@FrozenHaxor pointed this out to me earlier today.

I found [this](https://github.com/SteamRE/SteamKit/issues/90).  So presumably we just need to update to the latest SteamKit?

**Comment by FrozenHaxor** [comment]
Yes. Updating SteamKIT has solved the issue. People can use this to instantly crash the whole application.

**Comment by WildCard65** [comment]
Doesn't steambot already use SteamKit2 1.6.2?

**Comment by scholtzm** [comment]
We are definitely using the latest SteamKit available via NuGet.

b8848ea05c907259e9f81347434173bba982dcc6

**Comment by BlueRaja** [comment]
Well then nevermind :)
