### ISSUE TITLE
 Trade Error Trade with xxxx expired because other user timed out

### ISSUE THREAD

**Issue by vodcms** [Jessecar96/SteamBot#695]
my bot many to WARN: Trade with xxx expired because other user timed out .

when user accept trade . 3 -10 sec ago. bot print this error.

my bot setting
MaximumTradeTime = 180;
MaximiumActionGap = 300;
TradePollingInterval = 500;

pls help me fix it

**Comment by scholtzm** [comment]
#427 & #527
