### ISSUE TITLE
Bot add item error

### ISSUE THREAD

**Issue by vodcms** [Jessecar96/SteamBot#696]
when bot add item to other, Trade.additem sometimes response error,

like {"success":false,"error":"Unable to set item"}.

start trade i used validate cookie.

**Comment by debugger-perm** [comment]
Check assetid. Most error with wrong id.
15 янв. 2015 г. 15:21 пользователь "douma" <notifications@github.com>
написал:

**Comment by vodcms** [comment]
assetid is not woring. and sametimes response {"success":false,"error":"Could not find a trading session"}

**Comment by doktokto** [comment]
Maybe trade already closed but bot still trying to add item?

**Comment by vodcms** [comment]
i add time at OnTradeInit,so  is not trade already closed.

				Inventory my = Trade.MyInventory;

				if (my != null && my.Items.Count > 0) {


					foreach (Inventory.Item item in my.Items) {

						if (item.IsNotTradeable == false) {
							if (Trade.AddItemByDefindex (item.Defindex) == false) {
								if (Bot.CheckCookies () == false) {
									
									Trade.CancelTrade ();
									Bot.SteamClient.Disconnect ();
								}

							} else {
								break;
							}
						}
					}
				
			
				}

**Comment by vodcms** [comment]
I think is a BUG. Because it causes the robot trading instability.
ps: i todo auto trade,  trade offer need captcha at trades < 5000

**Comment by vodcms** [comment]
and add time sometime response {"success":false,"error":"missing required parameter"}

**Comment by scholtzm** [comment]
You shouldn't be calling `Bot.CheckCookies()` like that. **Cookie check is done automatically**, no need to do it manually.

Adding an item occasionally fails. This is due to Steam servers, network errors etc.

**Comment by vodcms** [comment]
thk @scholtzm 
But it too many errors, it is strange to invite transactions between users is good.

**Comment by doktokto** [comment]
I have same problems when my bots worked by standard trades. As I see, you adding all your inventory items. When bot trying to add them bot can't see what happend in trade, so if trade closed by other user bot will not know it. You can check it right now.

**Comment by doktokto** [comment]
Also when I make 2 bots add items when trade init - they just can't add items, I don't know why. But if first bot add in trade init, another bot add after it - all ok.
