### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by xEzitx** [Jessecar96/SteamBot#714]
Just saying thanks for your source, I've managed to convert this c# project to an android app and if it's okay with you I would like to release it so that people can run it from their phone :-), the app has a stylish GUI

Regards,

**Comment by WildCard65** [comment]
the fact that it's designed for people to make their own handlers for what they want the bot to do and that it requires a configuration, I don't think it'll work as expectedly as an android fact, along with I don't think SteamKit2 works with android.

**Comment by xEzitx** [comment]
I'm sure if I am able to port this to Android I'd be able to port a version of steamkit also, if not I could make it read from a file server on the internet for the steamkit dependacy's but that would cause my load times to be slow.
