### ISSUE TITLE
Unmanaged Resource leak

### ISSUE THREAD

**Issue by WildCard65** [Jessecar96/SteamBot#717]
Ok, after learning a bit about unmanaged resource, I know that there is a lack of PROPER disposing of unmanaged resource(Example: File logging of SteamBot) which isn't good. @BlueRaja @scholtzm What you guys think?

**Comment by scholtzm** [comment]
Wasn't there already some pull request which was taking care of disposing the logger?

**Comment by WildCard65** [comment]
You mean UpdateLogCapabilties? Still not merged yet.

**Comment by scholtzm** [comment]
Yeah, I see now.

**Comment by Jessecar96** [comment]
If there's anything that can be merged just let me know.  We need to clean up the PRs.  There's a bunch just sitting there with no updates for a while now.

**Comment by WildCard65** [comment]
I'm waiting for blueraja to give his opinions on the PR I sent for UpdateLogCapabilities.
