### ISSUE TITLE
Unable to access Inventory: Inventory is Private!

### ISSUE THREAD

**Issue by fr34kyn01535** [Jessecar96/SteamBot#722]
I am getting this error on every incoming trade using the ExampleBot:
https://screenshots.bam.yt/93baef7fa597c981878db443ec9bb3c7.png
The inventory on the trade bot is not private, it looks like it thinks that the *Trade.OtherInventory* is private..

```
[unturned.ROCKS 2015-02-23 00:31:26] WARN: Unknown error occurred: SteamTrade.Exceptions.TradeException: Unable to access Inventory: Inventory is Private!
   bei SteamTrade.Inventory.GetItem(UInt64 id) in c:\Users\fr34kyn01535\Documents\GitHub\SteamBot\SteamTrade\Inventory.cs:Zeile 78.
   bei SteamTrade.Trade.FireOnUserRemoveItem(TradeUserAssets asset) in c:\Users\fr34kyn01535\Documents\GitHub\SteamBot\SteamTrade\Trade.cs:Zeile 788.
   bei SteamTrade.Trade.HandleTradeVersionChange(TradeStatus status) in c:\Users\fr34kyn01535\Documents\GitHub\SteamBot\SteamTrade\Trade.cs:Zeile 697.
   bei SteamTrade.Trade.HandleTradeOngoing(TradeStatus status) in c:\Users\fr34kyn01535\Documents\GitHub\SteamBot\SteamTrade\Trade.cs:Zeile 599.
   bei SteamTrade.Trade.Poll() in c:\Users\fr34kyn01535\Documents\GitHub\SteamBot\SteamTrade\Trade.cs:Zeile 572.
   bei SteamTrade.TradeManager.<>c__DisplayClass6.<StartTradeThread>b__5() in c:\Users\fr34kyn01535\Documents\GitHub\SteamBot\SteamTrade\TradeManager.cs:Zeile 264.

**Comment by Bottswana** [comment]
Uuuuuuurm, I have no idea why it's doing that. I tested this >.>

**Comment by BlueRaja** [comment]
I tested the change too *(which was just merged today)*, and didn't not see this issue.

@fr34kyn01535  Could you give us the SteamID's of the bot and the other user, so we can attempt to replicate this?

**Comment by fr34kyn01535** [comment]
I will test this with another account tonight

**Comment by fr34kyn01535** [comment]
Ok the issue seems to be occuring if somebody has his whole steam profile private..

**Comment by scholtzm** [comment]
That is normal behaviour. Loading private inventories is *almost* impossible.

**Comment by BlueRaja** [comment]
If their profile is private, their inventory is necessarily also private.  So the exception is correct.
