### ISSUE TITLE
ArgumentNullException in Inventory.cs

### ISSUE THREAD

**Issue by bartico6** [Jessecar96/SteamBot#731]
Apparently sometimes the Items array is null?
>[Shaun The Sheep 2015-02-28 11:32:11] WARN: Unknown error occurred: System.ArgumentNullException: Argument cannot be null.
Parameter name: source
   in System.Linq.Enumerable.Where{TSource}(IEnumerable`1 source, Func`2 predicate)
   in SteamTrade.Inventory.GetItemsByDefindex(Int32 defindex) in X:\SteamBot-master\SteamTrade\Inventory.cs:line 79

Ideas?

**Comment by scholtzm** [comment]
You are using outdated SteamBot. This has been fixed.

**Comment by bartico6** [comment]
Happens randomly with my own inventory which is public though (close/reopen 'cause wrong button)

**Comment by scholtzm** [comment]
Well, hard to tell where the error is since the line 79 from your error output does not match with the [current codebase.](https://github.com/Jessecar96/SteamBot/blob/master/SteamTrade/Inventory.cs#L79)

**Comment by bartico6** [comment]
Running a version of inventory.cs w/o the new privatechecks in getItem and getItembydefindex, line 79 is this: 
`            return Items.Where(item => item.Defindex == defindex).ToList();`

**Comment by scholtzm** [comment]
Well, `Items` is null so the call fails.

In this case the inventory response must have been empty (?), although I don't remember this happening to me ever.

Would be probably best to log the actual response to see what's going on.

**Comment by bartico6** [comment]
I know it's null, that's why I opened an issue bro ;d
idk why this happens, as said it does randomly, with the bot's inventory - not some other user's. Pretty frickin weird, re-trading after the trade dies fixes it. I don't even ....
>That's why I'm a complete noob in networking

**Comment by scholtzm** [comment]
Well, there is not much that can be done. I suspect the API sometimes returns "200 OK" with response body `{ }`. We could either try to re-fetch the inventory (how many tries before we give up?) or just end the trade and try again which is IMO better option.

**Comment by bartico6** [comment]
Yea, what I hate the most about it is that users tend to quickly lose patiency, especially if they're in a hurry, so having something like that happen is pretty much -rep for the bot, like this one on my bot's profile:
>
Shadow 27 Feb @ 8:44pm 
-rep

Will later have a look at the inventory fetching thingy and re-try fetching a couple times.
If I find a good and reliable fix, I'll make a PR maybe, unless it's gonna be fixed by then. :P
