### ISSUE TITLE
steam auth command not working!

### ISSUE THREAD

**Issue by joshcannon** [Jessecar96/SteamBot#736]
When I try and start up the bot it tells me that I have steam-guard on and that I need to authenticate the account via the auth command. Well for me the auth command is yet to work . Does anyone have a fix for this ?

**Comment by WildCard65** [comment]
you doing something like this? auth <bot index here>=<steam code here>

**Comment by scholtzm** [comment]
The auth command works as intended. Please read the [usage guide](https://github.com/Jessecar96/SteamBot/wiki/Usage-Guide#bot-manager-commands) and make sure you are using the command correctly.

Also #427 and #527.

**Comment by joshcannon** [comment]
Can you give me a screenshot or something of how to use it ? I still can't figure out how to get mine to work.

**Comment by joshcannon** [comment]
nvm I got it to work finally !
