### ISSUE TITLE
Coding it so scrap bank for me 

### ISSUE THREAD

**Issue by Asbaat** [Jessecar96/SteamBot#737]
Hi, I was just getting a little "more" into scrap banking and saw that many people canceled their offers cuz I was too late to accept them so I wanted to make a bot, I read all of your guide to make the bot. I have made it, It works perfectly, It log-ins perfectly, I entered the steam Guard code too But the problem is that I don't know what is that bot supposed to do. Can someone guide me to make it scrap bank for me? Please!
Thank you so much,
M. Asbaat Amar

**Comment by FrozenHaxor** [comment]
This is not a personal helpdesk.

#427 #527

**Comment by Asbaat** [comment]
thanks for those links, I'll search there!

**Comment by Asbaat** [comment]
but they are closed already
