### ISSUE TITLE
Cant open the .sln

### ISSUE THREAD

**Issue by MilkGames** [Jessecar96/SteamBot#739]
For some reason i get this error, even more...
![fuckerror](https://cloud.githubusercontent.com/assets/10010026/6580502/5d68a9dc-c751-11e4-91a6-b9cb7a3da2f6.PNG)
![fuckerror1](https://cloud.githubusercontent.com/assets/10010026/6580503/5d724eba-c751-11e4-8156-43e0a29a6434.PNG)
![fuckerror2](https://cloud.githubusercontent.com/assets/10010026/6580504/5d737ab0-c751-11e4-9f9d-ee7b59e22486.PNG)

**Comment by FrozenHaxor** [comment]
That's because of #527. Also #427.

**Comment by MilkGames** [comment]
I think its just lazy to never help anyone, wow.

**Comment by scholtzm** [comment]
This is an issue tracker, you know.

Also, this is a C# project and you are using "Microsoft **Visual Basic** 2010 Express".

**Comment by BlueRaja** [comment]
I think it's lazy to not read the post that explains where you can go to get help, and just assume we *"never help anyone"*.
