### ISSUE TITLE
Steambot can't login on mono.

### ISSUE THREAD

**Issue by Obilux** [Jessecar96/SteamBot#741]
Hi i saw bot offline at morning and i try re-start bot and i can't open mono throw there errors  http://pastebin.com/qzt6FUEx Bot can work perfectly on windows

**Comment by FrozenHaxor** [comment]
Working just fine under mono here.

When you provide a paste, make sure we can actually see it...

**Comment by scholtzm** [comment]
No need to mirror [reddit posts](http://www.reddit.com/r/SteamBot/comments/2z54tk/steambot_cant_login/). Next time post here only if the problem is confirmed to be actual issue or a bug.

Also, obligatory #427 & #527.
