### ISSUE TITLE
 Steam began to ban bots?

### ISSUE THREAD

**Issue by doktokto** [Jessecar96/SteamBot#743]
Recently banned my bots. For more than two weeks I'm waiting for a response from support, but they are silent. Today banned probably the only bots that are left for Dota2, anyway I saw only them. Banned all accounts-bots and even main account of bots creator (I'm talking about Shop 261). Steam began to ban bots?

**Comment by BlueRaja** [comment]
#427 #527

**Comment by doktokto** [comment]
I can find how to add post to reddit :C
