### ISSUE TITLE
Wget error on Mac

### ISSUE THREAD

**Issue by L5hunter** [Jessecar96/SteamBot#744]
Hello, 
When I attempt to compile I get this error: 
var/folders/bk/sqxq4pw50lsb807cw8x865gc0000gn/T/tmp4586d973.tmp: line 1: wget: command not found
/Users/(my name)/Downloads/SteamBot-master/.nuget/NuGet.targets: error : Command 'mozroots --import --sync;wget -O '/Users/(my name)/Downloads/SteamBot-master/.nuget/NuGet.exe' https://nuget.org/nuget.exe' exited with code: 127.
			Task "Exec" execution -- FAILED

I have installed wget for mac, and also tried changing it to curl. Any workarounds here?

**Comment by BlueRaja** [comment]
#427 #527
