### ISSUE TITLE
Linux error

### ISSUE THREAD

**Issue by Pepsai** [Jessecar96/SteamBot#745]
Hey, i made a thread here ealier with some bugs in my bot. I think i have fixed every single problem. Now i want my bot to run on a linux machine running debian 7. But im getting some errors, is it because my machine is to weak? :) Errors when running: "mono SteamBot.exe" "http://gyazo.com/7df0b253d391031b7e1dacc7d2870747"
Edit: So here is what i tried: I tried on Ubuntu 10.04 Debian 6 Debian 7, and all have same error. I installed everything that is on the linux config page. I also tired "Sudo apt-get install mono-complete", and to compile mono myself, but no luck.

Posted on reddit with no luck.

**Comment by BlueRaja** [comment]
#427 #527
