### ISSUE TITLE
Bot doesn´t add Ref or Rec 

### ISSUE THREAD

**Issue by bartho2** [Jessecar96/SteamBot#747]
Hi @ all,

i made a key bot which was running without problems the last days. It is a Keybanking bot and every time when i add a key to sell (in the trade window) my bot came unresponsible.
the Days before Yesterday, everything worked fine. I was Able to sell and buy.

I added some text so i can test if the bot cann add metal.
when i write a pecific word in the Trade window the bot add metal (code below)

The bot can only add Scrap and no Rec of Ref.

Bot: https://steamcommunity.com/profiles/76561198167239072

the last time the bot was only able to add 10 ref (Bot had 60 Ref) and since i transfered the 10 Ref to another Acc the Bot isn´t adding Ref ??

---Source code---
public override void OnTradeMessage(string message)
        {
            Bot.log.Info("[TRADE MESSAGE] " + message);            
            message = message.ToLower();
            if (message == "givemescr")
            {
                Trade.SendMessage(" Ok i will do it");
                Bot.log.Warn("Admin is collecting Scr");
                Trade.AddItemByDefindex(5000);
            }
            if (message == "givemerec")
            {
                Trade.SendMessage(" Ok i will do it");
                Bot.log.Warn("Admin is collecting Rec");
                Trade.AddItemByDefindex(5001);
            }
            if (message == "givemeref")
            {
                Trade.SendMessage(" Ok i will do it");
                Bot.log.Warn("Admin is collecting Ref");
                Trade.AddItemByDefindex(5002);
            }

---Source code---

Sorry for my bad english
i hope anybody can help me

@scholtzm : I am no pro in programming, but the bot worked fine for several days. I did not change the code or restarted the exe and the bot isn´t working.

S: A Trade Problem ?
A: I logged in via Steam and traded a Friend some Ref - Worked fine.

S: My solution ended up being buying something off the Steam market with the bot.
A: I bouth a game with the bot last year (no gift)

**Comment by scholtzm** [comment]
#427 & #527

**Comment by BlueRaja** [comment]
It's very unlikely this is a bug in the bot, but I won't close this just in case.

I've seen something similar before, where the /inventory response was claiming my ref were untradable even though they weren't.  My solution ended up being buying something off the Steam market with the bot *(even though I had already traded for and used a "TF2 premium" item)*.

Could you link to the bot in question so we can check out its inventory?

**Comment by bartho2** [comment]
Solution:
Bought something on the TF2 Store and on Steam.

Thanks for help @BlueRaja
