### ISSUE TITLE
Getting System.NullReferenceException when using GetOffer()

### ISSUE THREAD

**Issue by rangersmash** [Jessecar96/SteamBot#748]
Hi.
I'm using TradeOfferManager.GetOffer() in a loop (code can be found here: http://pastebin.com/R8kesBkq) to check the status of an offer. However, whenever I use GetOffer with a valid offer ID from an offer that was sent 5 seconds ago, I seem to get a System.NullReferenceError when using get offer.
A picture of this error can be found here: http://i.imgur.com/qAdrU8w.png

Another thing I noticed is that TradeOfferManager is private in the bot and I had to change this variable to public so I could access these methods. I don't know if there is a better way to access these methods but this may have something to do with it.

**Comment by bartico6** [comment]
Buggy default code. Ahhh
You're getting an empty offer response, and you're attempting to get a property from a null object (you get a null object when deserializing an empty response).

**Comment by bartico6** [comment]
Here's the method in my code that actually works.
Have a look:
http://i.imgur.com/WhDjXrp.png

**Comment by BlueRaja** [comment]
I have not looked into SteamBot's trade-offer code yet, but:  if a trade offer was automatically created due to the other user having email notifications enabled, the response from the trade-offer API will be empty until that user accepts or declines the offer.  Thus an empty response should be an expected-case, not an error-case.

**Comment by bartico6** [comment]
Not really, trade offers created due to email confirmation enabled are normal offers with "from_real_time_trade" property set to true. However before the first user confirms their email there is no such offer sent yet, so I guess you're half right.

**Comment by BlueRaja** [comment]
The only case I've tested is "user initiates trade with bot," where the user has email confirmations and the bot doesn't.  The user **is** able to view the trade-offer via the API, but the bot **isn't**.

Are you saying if the bot initiates the trade, both users will be able to view the status of the trade-offer before the user accepts the offer via email-confirmation?

**Comment by rangersmash** [comment]
So is this just a issue with the email confirmation? What can I do to prevent the error?

**Comment by bartico6** [comment]
Nullchecks I guess.
BlueRaja, here's my point of view.

USER 1 initiates trade with USER 2:
Trade ends, user 1 has to confirm email.
>Trade does not exist, since you're sending it from email.
After user 1 confirmed his email, both users *should* see the offer as "awaiting email confirmation"
After user 2 confirmed - trade offer is accepted.

**Comment by BlueRaja** [comment]
Why would you have email confirmations enabled on your bot?

**Comment by rangersmash** [comment]
I don't have email confirmations on my bot. My friend is receiving the trade, showing the trade id & the trade is valid. However, when using GetOffer, I am still receiving a null result.

**Comment by scholtzm** [comment]
The problem is, that the trade offer doesn't really exist at that point. It's most likely created once the other person accepts/declines it via e-mail.

**Comment by rangersmash** [comment]
Okay. I just tested it with my friend accepting his email, yet it is still not finding the trade offer; classing it at null.

**Comment by scholtzm** [comment]
The API key is bound to bots account, right?

**Comment by rangersmash** [comment]
I am such an idiot. I was using a bot account except it had SteamGuard, so I changed the pass and stuff without the API key. Thank you!

**Comment by scholtzm** [comment]
While you are at it, if you call `GetOffer` before your friend accepts, does it return something?

**Comment by rangersmash** [comment]
Yes, it does return the TradeOffer.

**Comment by scholtzm** [comment]
Good to know.

**Comment by BlueRaja** [comment]
That's the exact opposite of what I observed.

**Comment by bartico6** [comment]
^ THIS IS A FAIL I MADE A LONG TIME AGO, CRINGING WHEN I FOUND OUT WHY HALF OF THE BOT DIDNT WORK.
Always check your APIKeys guys ;_____;
