### ISSUE TITLE
Running Steambot on Linux with "mono SteamBot.exe" results in "Unhandled Exception"

### ISSUE THREAD

**Issue by oappi** [Jessecar96/SteamBot#753]
Hi

Thanks for making such a awesome bot available for anyone to use and modify

My problem is that for some reason i cannot run SteamBot on my Linux mint 17 installation. 

mono -V result:

Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

mono SteamBot.exe result:

Unhandled Exception:
System.DllNotFoundException: Kernel32
  at (wrapper managed-to-native) SteamBot.Program:SetConsoleCtrlHandler (SteamBot.Program/HandlerRoutine,bool)
  at SteamBot.Program.BotManagerMode () [0x00000] in <filename unknown>:0
  at SteamBot.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: Kernel32
  at (wrapper managed-to-native) SteamBot.Program:SetConsoleCtrlHandler (SteamBot.Program/HandlerRoutine,bool)
  at SteamBot.Program.BotManagerMode () [0x00000] in <filename unknown>:0
  at SteamBot.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0

used repo version of mono, since it was high enough according to your documentation. Exactly same Steambot.exe works in windows 7, but when i copy whole folder to my mint machine, i got previous results. Then i "Created package" with Xamarin Studio for binaries and chose target platform "Linux".  I still get exactly same error message. Not sure if bug or did i do something wrong. Did not see similar case when i googled it. 

edit:
Tried to compile it in mint. It compiles the code with out problem, but crashes when i try to run it. Anyone got current version working on any linux distro (if so which)?

edit#2 doesn't work with opensuse 13.2 either (with all the latest updates) and mono 3.8. Only suggestions i find to errors i get is to  rewrite code with out windows dependent libraries. Btw it doesnt crash if i do not add settings json file.

**Comment by oappi** [comment]
Ah, figured out what was the error in my case 

"UseSeparateProcesses": "true" ..... doesnt seem to be linux friendly. Worked when i changed it to false.
Please inform this in https://github.com/Jessecar96/SteamBot/wiki/Configuration-Guide and preferably also in https://github.com/Jessecar96/SteamBot/wiki/Setting-Up-SteamBot-on-Linux as reminder.

**Comment by cymruu** [comment]
I think that using node version of steam-trade is better on linux
