### ISSUE TITLE
Decouple inventory with TF2 implementation.

### ISSUE THREAD

**Issue by nicolas-martin** [Jessecar96/SteamBot#754]
As of right now, the project is very strongly coupled with a TF2 specific inventory implementation.

I would like to see if you guys would be open to changes to allow greater flexibility. I was thinking of extracting the basic methods into an interface and using generics to insert the concrete item type needed. Where item is a the concrete item schema for that game.

```c#
    public interface IIventory<T> where T : IItem
    {
        List<T> FetchInventory(ulong steamId, string apiKey, SteamWeb steamWeb);
        T GetItem(ulong id);
        [...]
    }
```

Thoughts?

**Comment by scholtzm** [comment]
You can post this here: https://github.com/Jessecar96/SteamBot/issues/642

There have been some attempts, but never finished. *looks at @BlueRaja*

**Comment by nicolas-martin** [comment]
Yeah I saw that, but multi game support wasn't part of that OP. That's why I thought creating a new issue would be best. Should I just copy what I wrote into the other one?

**Comment by BlueRaja** [comment]
Multi-game support is the first bullet point...

**Comment by nicolas-martin** [comment]
Oh yeah my bad, wasn't very obvious. Should I move the discussion over there and close this one?
