### ISSUE TITLE
GitHub Compiling

### ISSUE THREAD

**Issue by 22minnis22** [Jessecar96/SteamBot#755]
Hello! I would like to start off with an apology, as this is not a SteamBot issue. Although my goal is to eventually move up from the given title, I am currently a massive GitHub and basically everything noob. I was hoping to download the bot and use trial and error to create a working bot (I don't actually want a bot, I am just in for the learning experience). Now, given that I am a huge noob, and I apologize if this is a cringe-worthly obvious question, but how do I compile the bot? I am new to Gits and Eclipse and all these things, so if anyone could kindly explain the process to me, I would be greatly appreciative. Thank you in advance, and have a nice day!

**Comment by nicolas-martin** [comment]
Eclipse is for Java this is a .Net project. Start by installing visual studio and hit F5 :)

**Comment by BlueRaja** [comment]
#427 #527
