### ISSUE TITLE
AntiVirus detecting trojan on build

### ISSUE THREAD

**Issue by WillHaskell** [Jessecar96/SteamBot#759]
SteamBot-master\SteamTrade\bin\Debug\SteamTrade.dll gets detected by ESET as a Stimilik.FZ Trojan.

Any ideas why?

**Comment by scholtzm** [comment]
Some people used SteamBot as a base for their scamming/phishing bots.

**Comment by DarkFlamex1** [comment]
agreed

**Comment by WillHaskell** [comment]
Hmm...

**Comment by BlueRaja** [comment]
Someone who actually owns the software will have to submit it as a false-positive to ESET.  Please include a link to the [source code](https://github.com/Jessecar96/SteamBot/tree/master/SteamTrade).

Not much else we can do.
