### ISSUE TITLE
Wrong JsonProperty in Inventory.cs

### ISSUE THREAD

**Issue by waylaidwanderer** [Jessecar96/SteamBot#761]
https://github.com/Jessecar96/SteamBot/blob/master/SteamTrade/Inventory.cs#L110

This should probably be `[JsonProperty("remaining_uses")]`, but I haven't checked the API to see what the actual key is.

**Comment by BlueRaja** [comment]
https://wiki.teamfortress.com/wiki/WebAPI/GetPlayerItems#Result_data
`quantity` is correct.

**Comment by waylaidwanderer** [comment]
Oh, you're right. Sorry, my bad. I was just browsing through the code and noticed the names didn't match.
