### ISSUE TITLE
Dota 2 Api Schema not working?

### ISSUE THREAD

**Issue by Tinario** [Jessecar96/SteamBot#762]
Dota 2 Api Schema not working

https://api.steampowered.com/IEconItems_570/GetSchema/v0001/?key=xxxxxxxxxxxxxxxxxxx

steam had changed, bcz its not showing anymore result.

any information about that?

**Comment by BlueRaja** [comment]
We only support the IEconItems API for TF2.  Use `GenericInventory` for Dota 2

**Comment by Kenny11CZ** [comment]
DotA2 schema is down for few months.

Look <a href="http://roshpit.ghost.io/getting-updated-item-schema-for-dota2-despite-app570econ-api-being-down-for-5-months/">here</a> for more informations.
