### ISSUE TITLE
Builded SteamTrade.dll = Virus

### ISSUE THREAD

**Issue by GAMELASTER** [Jessecar96/SteamBot#763]
Hey,

I have Windows 8.1 x64 (uncommon informations xd) with ESET antivirus. Still when i build SteamBot, ESET writes me the SteamTrade.dll is a virus, look a photo
![image](https://cloud.githubusercontent.com/assets/1665373/7773858/458f473c-00a7-11e5-9076-4164e4f42533.png)
Lol why and how to solve that? :-D

**Comment by FrozenHaxor** [comment]
Disable/remove the rubbish AV?

**Comment by GAMELASTER** [comment]
its not rubbish AV :-D I know, disable AV for that directory, but its really interesting, hmm, i just 4 fun taked it to VirusTotal and:
https://www.virustotal.com/en/file/f2324ed8dd314b4a70699398ca0b6dce0e62bdf7ac35d86b51fd6fc55a023710/analysis/1432309319/
xddd

**Comment by BlueRaja** [comment]
eset is actually a very good AV.  But we've discussed this before:  https://github.com/Jessecar96/SteamBot/issues/759
