### ISSUE TITLE
Error 401 Unauthorized error: null

### ISSUE THREAD

**Issue by koelen3** [Jessecar96/SteamBot#764]
The API key for the bot is working, here you find a screenshot of the error: http://i.imgur.com/d1LQ3zr.png

I have no clue how to fix this, both mine and the bot's API keys are working.

I got this before I posted, but it won't work

    public override void OnMessage(string message, EChatEntryType type)
        {
            message = message.ToLower();
            if (IsAdmin)
            {
                switch(message)
                {
                    case "!empty csgo":                        
                       var tradeOffer = TradeOffers.CreateTrade(OtherSID);
                            var myInventory = CSGOInventory.FetchInventory(MySID, Bot.apiKey);
                            foreach (var item in myInventory.Items)
                            {
                                tradeOffer.AddMyItem(item.AppId, item.ContextId, item.Id);
                            }
                            var tradeId = tradeOffer.SendTrade("");
                            if (tradeId > 0)
                            {
                                Bot.log.Success("Successfully sent a trade offer for all my items.");
                            }
                        break;
                    
                    case "!empty dota2":
                        var tradeOffer2 = TradeOffers.CreateTrade(OtherSID);
                            var myInventory2 = Dota2Inventory.FetchInventory(MySID, Bot.apiKey);
                            foreach (var item in myInventory2.Items)
                            {
                                tradeOffer2.AddMyItem(item.AppId, item.ContextId, item.Id);
                            }
                            var tradeId2 = tradeOffer2.SendTrade("");
                            if (tradeId2 > 0)
                            {
                                Bot.log.Success("Successfully sent a trade offer for all my items.");
                            }
                        break;

                    case "!empty tf2":
                        var tradeOffer3 = TradeOffers.CreateTrade(OtherSID);
                            var myInventory3 = TF2Inventory.FetchInventory(MySID, Bot.apiKey);
                            foreach (var item in myInventory3.Items)
                            {
                                tradeOffer3.AddMyItem(item.AppId, item.ContextId, item.Id);
                            }
                            var tradeId3 = tradeOffer3.SendTrade("");
                            if (tradeId3 > 0)
                            {
                                Bot.log.Success("Successfully sent a trade offer for all my items.");
                            }
                        break;
                }

            }
            else
            {
                Bot.SteamFriends.SendChatMessage(OtherSID, EChatEntryType.ChatMsg, Bot.ChatResponse);
            }
        }

If there is anything else you need, please let me know.

**Comment by BlueRaja** [comment]
This forum is for bug reports, but my first assumption is that this is user-error.  Have you dug into this to confirm this is a SteamBot bug?

**Comment by scholtzm** [comment]
@BlueRaja Seems like a modified SteamBot.

`TradeOffers.CreateTrade(OtherSID)` - I have never seen this method.

`CSGOInventory.FetchInventory(MySID, Bot.apiKey)` - not part of SteamBot either.

**Comment by koelen3** [comment]
Yeah it's a modified bot.
I use the Steambot and the CSGOShop.com bot combined for my bot.

I'll post the tradeoffer file in a bit

**Comment by BlueRaja** [comment]
#427

**Comment by koelen3** [comment]
I found that more people respond here then on the subreddit.

**Comment by ThereWasADream** [comment]
It's still only for bug reports. You will probably be better off reading
and researching for a few hours and solving the bug yourself. I find when I
get no response on the subreddit I usually end up solving the issue after a
few hours of research.

**Comment by koelen3** [comment]
I'm already looking for three days and didn't found an answer that's why I posted on both

**Comment by ThereWasADream** [comment]
Come back with proof it's a bug. Good luck! :)

**Comment by waylaidwanderer** [comment]
Looks like you're using my fork. I find that interesting because I haven't released it publicly, aside from using it in some freelance projects. Steam changed some parameters a long time ago for trade offers. I've updated my code locally but you're using an older version.

Can I ask where you got your SteamBot from?

**Comment by scholtzm** [comment]
He's using the CSGOShop bot.

**Comment by koelen3** [comment]
@waylaidwanderer
It's the CSGOShop bot from OhMatty, but I've been compiling my own bot from the Steambot and CSGOShop bot

**Comment by waylaidwanderer** [comment]
Yeah, I wrote the CSGOShop bot. I'd recommend you not use it because it's pretty outdated.

**Comment by BlueRaja** [comment]
We fixed some bugs in the last 6-12 months that could allow scammers to steal all your bot's stuff.  Make sure you're using the latest version of SteamBot.

**Comment by koelen3** [comment]
@waylaidwanderer I'll contact you in a second
@BlueRaja Yeah, that's why I'm getting errors now, because I'm updating the bot to the newest SteamBot version

**Comment by waylaidwanderer** [comment]
@BlueRaja @koelen3 If you're just using SteamBot for trade offers, those bug fixes doesn't really matter since they only affect direct/live trading.

I'm thinking of pushing my updated code to my fork, it's working pretty well for me (it actually works as a generic "Steam" bot and not a "TF2" bot in terms of live trading), and my own trade offers library is just one file instead of @StormReaper's folder.
