### ISSUE TITLE
[NOT ACTUALLY AN ISSUE] Create a branch only for trade offers

### ISSUE THREAD

**Issue by krystalgamer** [Jessecar96/SteamBot#766]
How about we create a branch for the trade offer that waylaid released?

**Comment by BlueRaja** [comment]
I assume you mean a pull request?  Do you have a link to whatever it is you're talking about?

**Comment by krystalgamer** [comment]
https://github.com/waylaidwanderer/SteamTradeOffersBot

No, actually mean branch. Having all in the same git repository will be better in my opinion.

It can be called "trade-offers-only" or something like that.

**Comment by BlueRaja** [comment]
No, it does not make sense to create a branch for that here.  The branch should only be maintained in one place, in the repository of whoever is working on it.

If it ever gets to the point where it meets the [minimum criteria](https://github.com/Jessecar96/SteamBot/issues/642) for a good-yet-breaking-change inventory, I'd recommend he (or anyone else) create a PR to merge it here.  That is the Github workflow.
