### ISSUE TITLE
Bot cannot find my settings.json

### ISSUE THREAD

**Issue by AShyHyena** [Jessecar96/SteamBot#767]
I'm stumped, I've compiled the program and everything and renamed my "settings-template.json" to "settings.json" and it still won't work. I don't understand the problem!

**Comment by BlueRaja** [comment]
Put it in the same directory as the .exe

Also #427

**Comment by AShyHyena** [comment]
It is though...

**Comment by AShyHyena** [comment]
http://puu.sh/iwSAi/a43749569a.png

**Comment by BlueRaja** [comment]
Step through using the debugger to determine where in the loading process it's failing.

**Comment by scholtzm** [comment]
What is the exact error you are getting?
