### ISSUE TITLE
Integration on ASP website 

### ISSUE THREAD

**Issue by geekspod** [Jessecar96/SteamBot#768]
1: How can this be used for trading just like csgo jackpot site?
2: How will this be integrated on an ASP website? How can the responses of the bot be displayed on the browser?
3: Which server is preferred for this job and how to do it?

I want to make trading just like www.csgojackpot.com using this steam bot  for my asp.net site and how to integrate it with my asp.net site.

**Comment by BlueRaja** [comment]
#427 #527
