### ISSUE TITLE
SteamTrade.dll detected as virus by microsoft security essentials. why?

### ISSUE THREAD

**Issue by Tinario** [Jessecar96/SteamBot#769]
there is no malicious code in this source, its used to manage the trade platform session, why is giving this error and how to fix it?

![steamtrade](https://cloud.githubusercontent.com/assets/5225537/8387073/3caba426-1c2c-11e5-8c5d-855f53b1c47a.png)

**Comment by BlueRaja** [comment]
https://github.com/Jessecar96/SteamBot/issues/759
