### ISSUE TITLE
Freshly cloned and compiled SteamBot results in antivirus warning(PWS:MSIL/Stimilini.F in SteamTrade.dll)

### ISSUE THREAD

**Issue by lazy1** [Jessecar96/SteamBot#770]
I cloned https://github.com/Jessecar96/SteamBot and compiled it with Visual Studio 2013 Express for Windows Desktop.

Upon compilation Microsoft Security Essentials pops up a warning that freshly compiled "obj\Debug\SteamTrade.dll" contains malware: 
http://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=PWS%3aMSIL%2fStimilini.F&threatid=2147692617&enterprise=0

Did anybody experienced this problem before?
If not could anybody reproduce it with VS2013 and MSE?

**Comment by scholtzm** [comment]
#759

**Comment by lazy1** [comment]
Thanks.
