### ISSUE TITLE
SteamWeb.cs bug?

### ISSUE THREAD

**Issue by KriBetko** [Jessecar96/SteamBot#771]
To gain access to the site Steam tried to use the method DoLogin (), but all the time he returns captcha_needed = true. What's wrong?
Captcha I correctly insert the data from the profile is also true.
I apologize for the bad english.

**Comment by scholtzm** [comment]
Don't use the method, it's outdated and deprecated. SteamBot doesn't use it for logging in either.

**Comment by KriBetko** [comment]
And where you can find an example of a working login?
Other methods also outdated?

**Comment by scholtzm** [comment]
SteamBot uses this method to authenticate: https://github.com/Jessecar96/SteamBot/blob/master/SteamTrade/SteamWeb.cs#L201

**Comment by KriBetko** [comment]
Thanks. But I have a question about the variables passed to the class Authenticate.
"myUniqueId" is Id. And then what "myLoginKey"? And that takes a variable "client"?
I read the comments near this method but there is nothing about this.

**Comment by WildCard65** [comment]
https://github.com/Jessecar96/SteamBot/blob/master/SteamBot/Bot.cs#L718 will be helpful.
