### ISSUE TITLE
Setting.json issues when starting

### ISSUE THREAD

**Issue by coolxlfc289** [Jessecar96/SteamBot#779]
http://prntscr.com/7whij1

This is what happens when i try and start my bot.

**Comment by scholtzm** [comment]
The problem couldn't have been any clearer. What would you like us to do?

#427 #527

**Comment by coolxlfc289** [comment]
I would for someone like yourself to help me on what to do, I don't have the settings-template file, and I think I have filled it out correctly. But I arent 100% sure

**Comment by coolxlfc289** [comment]
I aren't sure why this was closed?
