### ISSUE TITLE
Settings issue

### ISSUE THREAD

**Issue by coolxlfc289** [Jessecar96/SteamBot#780]
http://prntscr.com/7whij1

I still have this issue, any chance someone could help me with it please instead of randomly closing my thread.

Thanks

**Comment by BrokenSilence** [comment]
If you do not know what that means, that you probably shouldn't be messing
with SteamBot.

2015-07-24 17:21 GMT+01:00 coolxlfc289 <notifications@github.com>:

**Comment by coolxlfc289** [comment]
Think positively when trying to do new things instead of thinking that someone can not do something. If you are so smart, why not help me out? Or is posting comments like that more helpful than teaching someone? I wonder...

**Comment by BlueRaja** [comment]
This is an issue tracker, not a help forum.  You were directed to the help forum in the previous issue #779.
