### ISSUE TITLE
where to start? Which steam api calls do I really need?

### ISSUE THREAD

**Issue by alpham8** [Jessecar96/SteamBot#785]
Hi,
I googled a lot on how to make a steam bot, which can send users trade offers. But I did not really find much about it. Or, as in this case, too much ;-)

So please tell me where I can find in your huge project examples for the steam API calls. I just need login, trade offers and logout. That´s all. Please show me it. I am familiar with C#, but I need to translate it into php.

**Comment by benjibobs** [comment]
#427 

However, rewriting this in php is a massive project in itself, I would suggest taking a look at a node.js steam bot instead, it may be easier

**Comment by alpham8** [comment]
Yes thanks, but you did not understand me right. I just need some parts of it. Only authentification (login/logout) and trading requests.

**Comment by SephirothSG** [comment]
As was suggested before #427 also take a look at [node-steam](https://github.com/seishun/node-steam) and its related modules.
