### ISSUE TITLE
Bot still reinitializing a Instance Class

### ISSUE THREAD

**Issue by GAMELASTER** [Jessecar96/SteamBot#792]
Hello,

I have Bot class, in class constructor i have initializing of MySQL connection etc etc.. 
```
public botClass(Bot bot, SteamID sid)
            : base(bot, sid)
{
Log.Debug("Initialized");
...
```
But, when Steam Trade Offer commes, and OnNewTradeOffer ends, the botClass is reinitialized, so again it write a "Initialized".

How to disable this feature or where i can a initialize a main stuff?

Thanks

**Comment by BlueRaja** [comment]
...what?

**Comment by scholtzm** [comment]
SteamBot creates unique *UserHandler* instance per user. Either make your stuff static or modify `Bot.cs`.

**Comment by waylaidwanderer** [comment]
This is not a bug. If you want it to be run only once, put the code in `OnLoginCompleted`, and make sure you use a condition like `if (!connectedAlready)` because re-authentication might also cause `OnLoginCompleted` to run again (not quite sure if this is the case, but best to be safe).
