### ISSUE TITLE
Downloading schema fails if bot profile is private

### ISSUE THREAD

**Issue by Kristopher38** [Jessecar96/SteamBot#794]
As in the title, when bot profile is set to private, downloading schema times out with error (Timeout expired):

    [botname 2015-08-23 12:46:19] INFO: Downloading Schema...
    [botname 2015-08-23 12:51:22] ERROR: URI: unknown >> System.Net.WebException: Upłynął limit czasu operacji.
       w System.Net.GZipWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 size)
       w System.Net.Cache.ForwardingReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
       w System.IO.StreamReader.ReadBuffer()
       w System.IO.StreamReader.ReadToEnd()
       w SteamTrade.Schema.GetSchemaString(HttpWebResponse response, DateTime schemaLastModified) w c:\Users\Krzychu\Downloads\SteamBot-master\SteamBot-master\SteamTrade\Schema.cs:wiersz 76
       w SteamTrade.Schema.FetchSchema(String apiKey, String schemaLang) w c:\Users\Krzychu\Downloads\SteamBot-master\SteamBot-master\SteamTrade\Schema.cs:wiersz 56
       w SteamBot.Bot.<HandleSteamMessage>b__5(LoginKeyCallback callback) w c:\Users\Krzychu\Downloads\SteamBot-master\SteamBot-master\SteamBot\Bot.cs:wiersz 451
       w SteamKit2.CallbackMsgExtensions.Handle[T](ICallbackMsg msg, Action`1 handler)
       w SteamBot.Bot.HandleSteamMessage(ICallbackMsg msg) w c:\Users\Krzychu\Downloads\SteamBot-master\SteamBot-master\SteamBot\Bot.cs:wiersz 442
       w SteamBot.Bot.BackgroundWorkerOnDoWork(Object sender, DoWorkEventArgs doWorkEventArgs) w c:\Users\Krzychu\Downloads\SteamBot-master\SteamBot-master\SteamBot\Bot.cs:wiersz 925

Or with (existing connection was forcibly closed by the remote host):

    [botname 2015-08-23 12:52:40] INFO: Downloading Schema...
    [botname 2015-08-23 12:53:03] ERROR: System.IO.IOException: Nie można odczytać danych z połączenia transportowego: Istniejące połączenie zostało gwałtownie zamknięte przez zdalnego hosta. ---> System.Net.Sockets.SocketException: Istniejące połączenie zostało gwałtownie zamknięte przez zdalnego hosta
       w System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
       --- Koniec śladu stosu wyjątków wewnętrznych ---
       w System.Net.GZipWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 size)
       w System.Net.Cache.ForwardingReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
       w System.IO.StreamReader.ReadBuffer()
       w System.IO.StreamReader.ReadToEnd()
       w SteamTrade.Schema.GetSchemaString(HttpWebResponse response, DateTime schemaLastModified) w c:\Users\Krzychu\Downloads\SteamBot-master\SteamBot-master\SteamTrade\Schema.cs:wiersz 76
       w SteamTrade.Schema.FetchSchema(String apiKey, String schemaLang) w c:\Users\Krzychu\Downloads\SteamBot-master\SteamBot-master\SteamTrade\Schema.cs:wiersz 56
       w SteamBot.Bot.<HandleSteamMessage>b__5(LoginKeyCallback callback) w c:\Users\Krzychu\Downloads\SteamBot-master\SteamBot-master\SteamBot\Bot.cs:wiersz 451
       w SteamKit2.CallbackMsgExtensions.Handle[T](ICallbackMsg msg, Action`1 handler)
       w SteamBot.Bot.HandleSteamMessage(ICallbackMsg msg) w c:\Users\Krzychu\Downloads\SteamBot-master\SteamBot-master\SteamBot\Bot.cs:wiersz 442
       w SteamBot.Bot.BackgroundWorkerOnDoWork(Object sender, DoWorkEventArgs doWorkEventArgs) w c:\Users\Krzychu\Downloads\SteamBot-master\SteamBot-master\SteamBot\Bot.cs:wiersz 925
    [botname 2015-08-23 12:53:03] WARN: Restarting bot...

Setting bot profile to public fixes that issue, but I suggest displaying exact information to the user what might have caused this error, as it may be confusing sometimes, especially for new users.

**Comment by scholtzm** [comment]
That is weird? Schema is downloaded from the API which is not affected by profile visibility. The issue must be elsewhere.

**Comment by Kristopher38** [comment]
Hmm, I reversed it back, and now it works with private profile, though back when I was trying to fix it, changing profile visibility from private to public solved the issue. I did not take a long breaks between above attempts to make the bot work, but this might have been steam unavailability at that time (though I don't really feel that was it).

**Comment by Jessecar96** [comment]
Looks to be a Steam issue and not a SteamBot one.
