### ISSUE TITLE
Bot not accepting incoming trade offer

### ISSUE THREAD

**Issue by vanqaaa** [Jessecar96/SteamBot#795]
Hi! for first thanks for the bot, but i'm have difficulties with configuring, i have set loggin settings and past Steam guard file from steam, all seems working fine, but when offline offers come, bot don't do it anything (Sorry for my English)

[Tim 2015-08-24 20:15:22] SUCCESS: Done Loading Bot!
[Tim 2015-08-24 20:15:27] SUCCESS: User Authenticated!
[Tim 2015-08-24 20:15:27] INFO: Downloading Schema...
[Tim 2015-08-24 20:15:28] SUCCESS: Schema Downloaded!
[Tim 2015-08-24 20:15:28] SUCCESS: Steam Bot Logged In Completely!
[Tim 2015-08-24 20:15:45] INFO: TradeOffer notification (This appers when offer comes)

Settings file:

"Admins":["steam id"],
"ApiKey":" my api",
"mainLog": "syslog.log",
"UseSeparateProcesses": "false",
"AutoStartAllBots": "true",
"Bots": [
        {
            "Username":"login",
            "Password":"mypw",
            "ApiKey":" my api",
            "DisplayName":"Tim",
            "ChatResponse":"Hi",
            "logFile": "TestBot.log",
            "BotControlClass": "SteamBot.AdminUserHandler",
            "MaximumTradeTime":40,
            "MaximumActionGap":20,
            "DisplayNamePrefix":"",
            "TradePollingInterval":800,
            "ConsoleLogLevel":"debug",
            "FileLogLevel":"Info",
            "AutoStart": "true",
            "SchemaLang":"en"

**Comment by scholtzm** [comment]
Have you configured your userhandler?

**Comment by vanqaaa** [comment]
Hello! Appreciate for you fast answer, now i see it's was problem in wrong handler selected by me, just now changed it to "TradeOfferUserHandle" and bot immediately declines trade, in log bot says this

[Tim 2015-08-24 20:45:37] INFO: Declined trade offer : 659683859 from untrusted user 76561198228454024

So i just research TradeOfferUserHandle to try allow to trade with untrusted, but cant find anything :( 
Could You help me please?

**Comment by BlueRaja** [comment]
#427

**Comment by vanqaaa** [comment]
what a nice guy
