### ISSUE TITLE
declining trade

### ISSUE THREAD

**Issue by haroko12345** [Jessecar96/SteamBot#798]
hey i have this error
![err bot](https://cloud.githubusercontent.com/assets/14159353/9712808/a1bf632a-554d-11e5-9f2a-8afaf1826ba6.png)

what is wrong?

**Comment by scholtzm** [comment]
Your code is printing the error message and that's not a SteamBot issue.

**Comment by BlueRaja** [comment]
This is a message your bot is printing...
