### ISSUE TITLE
OnTradeSuccess doesn't fire correctly ?

### ISSUE THREAD

**Issue by Arkarr** [Jessecar96/SteamBot#799]
I have downloaded the bot once again, and changed nothing to the code. BUT I disabled the email verification on the bot (wich should be a problem, is it ?).

After I sucessfully create the trade (via the window where we can move our items) and we both accepted the trade offer, I go to my mails, and select : "Accept trade offer". Then, the trade goes well, both of use get the items except that the bot never go inside of 'OnTradeSuccess' in the UserHandler class.

Is it just me ? Did I miss something ? Please help me D: !

**Comment by scholtzm** [comment]
`OnTradeSuccess` won't fire if at least one of the participants has the e-mail confirmations enabled.

You can use [`OnTradeAwaitingEmailConfirmation`](https://github.com/Jessecar96/SteamBot/blob/master/SteamBot/UserHandler.cs#L243) but you still won't know if or when the trade offer (via e-mail) gets accepted.

**Comment by Arkarr** [comment]
Well...No way to counter that, yet, I guess ?

**Comment by scholtzm** [comment]
You can check the trade offer status over and over and that's about it. Doesn't matter what language or platform you are using.

**Comment by Arkarr** [comment]
Mind to tell me how I can do that ? I saw your tradeManager class there, but I don't think creating a Object TradeManager in SimpleUserHandler is a good idea. Where should I create it ? Create a whole new class to do that job ?

I'm totally not familiar whith (your?) bot / code (well, I didn't inspected the code for long...)

**Comment by scholtzm** [comment]
You probably just need to call  [`TryGetTradeOffer`](https://github.com/Jessecar96/SteamBot/blob/master/SteamBot/Bot.cs#L313) with the `offerId` from `OnTradeAwaitingEmailConfirmation`.

**Comment by Arkarr** [comment]
Back

But this methode return a boolean ? What should we do with that ?

**Comment by scholtzm** [comment]
```cs
var offer = Bot.NewTradeOffer(new SteamID());
var success = TryGetTradeOffer("123456", out offer);
// check offer.TradeOfferState
```

The implementation is far from ideal though.

**Comment by Arkarr** [comment]
Thanks !
This is what I have so far :

SimpleUserHandler constructor :
```listIDTradeOffer = new List<long>();
            ThreadStart threadDelegate = new ThreadStart(ReadTradeOfferStatus);
            Thread checkTradeOffer = new Thread(threadDelegate);
            checkTradeOffer.Start();```


```public void ReadTradeOfferStatus()
        {
            while(true)
            {
                foreach(long id in listIDTradeOffer)
                {
                    var offer = Bot.NewTradeOffer(new SteamID());
                    var success = Bot.TryGetTradeOffer(id.ToString(), out offer);
                }
            }
        }```

**Comment by WildCard65** [comment]
@scholtzm This implementation is actually:
```
TradeOffer offer = null;
bool success = Bot.TryGetTradeOffer(id.toString(), out offer);
```

**Comment by scholtzm** [comment]
@WildCard65 I was talking about the implementation of the actual method.

You just rewrote my snippet in slightly different way but it doen't do anything differently.
