### ISSUE TITLE
NodeSteam Sentry file to SteamBot Sentry file

### ISSUE THREAD

**Issue by GAMELASTER** [Jessecar96/SteamBot#800]
Hi,

i trying to get a (i though) a SSFN Sentry file for SteamBot from sentry file from NodeSteam. I readed something about SHA1 but in way to NodeSteam Sentry, but i dont know how to reverse this process. How to do that?

Thankie

**Comment by BlueRaja** [comment]
https://github.com/Jessecar96/SteamBot/pull/667

If you could fix the merge conflicts and create a new PR, I'm sure other people would appreciate it as well.  You're not the first to ask for this.

**Comment by GAMELASTER** [comment]
#801

**Comment by hnkent** [comment]
Is there any way to convert sentry files of Steam Bot to NodeJs? Thanks.

**Comment by scholtzm** [comment]
You don't need to convert anything. When logging in, [calculate the SHA-1 and pass that to `sha_sentryfile` as you normally should](https://github.com/scholtzm/vapor/blob/master/lib/events/connected.js#L16-L19).
