### ISSUE TITLE
node steam tradebot not accepting offers

### ISSUE THREAD

**Issue by neoxdany** [Jessecar96/SteamBot#809]
Errors help me thank you
![vystrizek](https://cloud.githubusercontent.com/assets/14570752/9993494/6b73f61a-6078-11e5-935e-0b1ba382c8d7.PNG)

offers.acceptOffer({tradeOfferId: offer.tradeofferid});															
console.log('Accepted trade offer #'+offer.tradeofferid+' by '+name+' ('+offer.steamid_other+')');

**Comment by FrozenHaxor** [comment]
Lol, that's a first one.

When will people stop randomly downloading software expecting to double click on it and hoping for easy money...

**Comment by neoxdany** [comment]
Thanks for your help FroxenHaxor

**Comment by scholtzm** [comment]
> node.js platform
> mysql error
> leaked bot code

Ready to be closed @BlueRaja.

**Comment by BlueRaja** [comment]
:+1:

**Comment by TheAnthonyNL** [comment]
This is so funny ... anyway to fix that error make sure the database tables contains data LOL.

**Comment by neoxdany** [comment]
the database is all well

**Comment by TheAnthonyNL** [comment]
Im 100% sure it isnt cause i haf samw problem. Still bot and site are broken dont even mess with them. Just build your own one.

**Comment by neoxdany** [comment]
For three days now I try to somehow correct the error and add to the already really know

**Comment by ThereWasADream** [comment]
I know I've been guilty of this myself but per the rules the only person who should have replied here is BlueRaja to close this. If it's not a bug report just ignore it and let someone close it.

Besides, it's not like someone who doesn't bother to try and learn c# before starting a project like this, nor read the rules before posting is going to read a comment that doesn't give a super easy solution. Someone ban neoxdany so we can all move on and await an actual bug report.

**Comment by BlueRaja** [comment]
It's not even that this isn't a bug report, it's not even for this project.  He's using Node-steambot, which isn't even C#.

**Comment by neoxdany** [comment]
Apologies and thanks
LOCK please
