### ISSUE TITLE
Long loading part of site (pot with items)

### ISSUE THREAD

**Issue by wygasmateusz** [Jessecar96/SteamBot#814]
Hello !

I have a another problem .

I install everything like in tutorial work perfectly but ...

Part of site  -  container with pot info ( items in pot , placed items ) stuck on loading... over 20-30 secound.
Any one have issue like that ? I will be greatfull for any suggest :)

Thanks !
Additional info :
It is on  VPS with core 2 duo / 2 GB or Ram / and 100MB/s network
Lastest PHP and MSQL

**Comment by FrozenHaxor** [comment]
What on the earth is this?

#427 I suppose.

**Comment by waylaidwanderer** [comment]
You are probably looking for https://github.com/ztizzlegaming/CSGOWinBig

Post there instead.
