### ISSUE TITLE
TheirOfferedItems empty after getting the offer with TryGetTradeOffer()

### ISSUE THREAD

**Issue by Arkarr** [Jessecar96/SteamBot#815]
```C#
string id = "ID_OF_THE_TRADE";
TradeOffer offer = null;
 bool success = TryGetTradeOffer(id, out offer);
 if (success)
 {
     if (offer.OfferState == TradeOfferState.TradeOfferStateAccepted)
     {
             int count = offer.Items.GetTheirItems().Count; //count == 0 /!\ !!!
     }
}
```
I am doing something wrong ?

**Comment by bartico6** [comment]
Are "your items" not-empty?
More debug info. Also this should be asked on reddit: [HERE](http://reddit.com/r/SteamBot)

**Comment by Arkarr** [comment]
Yup, my items list is also empty. Thanks for the reddit link. So should I create a new thread there ?

**Comment by Arkarr** [comment]
https://www.reddit.com/r/SteamBot/comments/3mswwp/theiroffereditems_empty_after_getting_the_offer/

**Comment by bartico6** [comment]
You possibly do not have access to the offer. Maybe you're using a Apikey assigned to your account, and not the bot's?

**Comment by Arkarr** [comment]
I'm using the one in the config file, so, the one linked to my account, I guess. Is that wrong ?

**Comment by scholtzm** [comment]
Why are you guessing? Config file doesn't come with an API key.

https://github.com/Jessecar96/SteamBot/blob/master/Bin/Debug/settings-template.json#L11

**Comment by scholtzm** [comment]
btw. This is not a SteamBot issues so #427 / #527 and continue in the subreddit.

cc @BlueRaja

**Comment by Arkarr** [comment]
Totally true, I didn't know about #427, and well, I shouldn't have used the word 'guess'. Sorry.

**Comment by scholtzm** [comment]
You didn't 'piss me off'. :grinning: 

If this turns out to be an actual issue, it can be re-opened.
