### ISSUE TITLE
Hw to hadle event when someone connects to steam and got showed in friends list

### ISSUE THREAD

**Issue by iamcsharper** [Jessecar96/SteamBot#817]
Well, I'll start introduction from an apology for grammar mistakes.
How can I track when bot's friend becomes active? For a live example, bot called Jessica has got a message that Hiron has become active, and Jessica sends a hello message.
I need to implements this for loading inventory. I use your steambot to create another one, which will act like a Jarvis in "Iron Man", and one of functions is show some items in my inventory by the command.

Of course, if you know how to implement my idea by another way, pls, reply!

Thanks in advance, Hiron.

**Comment by BlueRaja** [comment]
#427
