### ISSUE TITLE
JSON accountid_other is me ?!

### ISSUE THREAD

**Issue by Arkarr** [Jessecar96/SteamBot#820]
I'm trying to get the steam ID of the partner of my trade offer. The problem is that the 'accountid_other' is my bot account id !

At first, I tought it was my fault, but after debuging a bit, I found the "Offer" class inside the "TradeOfferWebApi" class and noticied that the property retourned by JSON is definitly my bot ID !

Can anyone confirm this ?

**Comment by scholtzm** [comment]
Problem is definitely on your end. The SteamID mapping in SteamBot `TradeOffer` class is correct.

**Comment by Arkarr** [comment]
Alright, well, I will redownload the bot and see if I have the same bug. Anyway, this shoul be correct, right ?
1) I invite someone to trade
2) We both add something to trade
3) I accept the trade offer
4) I confirm through my emails
5) "accountid_other" is the id of the guy I invited to trade with.

**Comment by scholtzm** [comment]
> "accountid_other" is the id of the guy I invited to trade with

That's expected. (?)

**Comment by Arkarr** [comment]
Just to be sure...

**Comment by Arkarr** [comment]
Well, I don't really think it's my fault, because ID is wrong inside OnTradeAwaitingEmailConfirmation(long tradeOfferID) !
```javascript
public override void OnTradeAwaitingEmailConfirmation(long tradeOfferID)
        {
            Log.Warn("Trade ended awaiting email confirmation");
            SendChatMessage("Please complete the email confirmation to finish the trade");

            SteamTrade.TradeOffer.TradeOffer offer = null;
            bool success = Bot.TryGetTradeOffer(tradeOfferID.ToString(), out offer);
            if(success)
            {
                SteamKit2.SteamID test = offer.PartnerSteamId;
            }
        }
```
I didn't edited anything...

**Comment by scholtzm** [comment]
Well, you already know other user's SteamID - it's `OtherSID`, inside your userhandler.

If `PartnerSteamId` equals bot's SteamID, it's Steam sending this information.

**Comment by Arkarr** [comment]
Alright, that's why. Thanks. But, actually, there is no way to get the PartnerSteamID inside the "Bot" class, right ? Because I'm doing the code above to get the trade offer inside the "Bot" class and I need to get the other player inventory to check wich items have been traded. Is their a way to do that ?

**Comment by scholtzm** [comment]
The snippet above won't work very well. You are retrieving the trade offer right after regular trading session ends. The trade offer will be in pending state.

Btw. You already know the list of items from the trading session.

**Comment by Arkarr** [comment]
> Btw. You already know the list of items from the trading session.
Yeah, but I need to retrieve it when the user confirmed the trade via his emails.

**Comment by scholtzm** [comment]
1. That's OK, but the snippet is still invalid.

2. Why do you need the same list of items? It's doable of course.

**Comment by Arkarr** [comment]
the part 1. is working fine, so I guess, I shouldn't update my sniper (do I have to ? I can.)
2. I don't really get it, I just try to get wich items has been traded between users after trade offer has been confirmed via emails. That's it.

**Comment by Arkarr** [comment]
Also, this is working fine http://api.steampowered.com/IEconService/GetTradeOffer/v1/?key=AFCE0097A6C1DA09D0DD671CC9338542&tradeofferid=757379315&language=en

but this isn't : http://api.steampowered.com/IEconService/GetTradeOffer/v1/?key=AFCE0097A6C1DA09D0DD671CC9338542&tradeofferid=757657228&language=en

Why ?
