### ISSUE TITLE
steambot.exe dont appear

### ISSUE THREAD

**Issue by burqka** [Jessecar96/SteamBot#821]
Hello,
I have installed SteamBot on my VPS, i have done all from the installation guide for Centos (linux), but I  don't have SteamBot.exe file into my SteamBot/Bin/Release or Bin folder. What I have done wrong?
1. Installed NuGet2 and compiled
2. Installed mono latest version and compiled
3. Installed SteamBot and compiled
4. Removed git-clone, git and installed them again and cloned.

All I have done, nothing shows up there.. Maybe someone can give me some advice?

**Comment by FrozenHaxor** [comment]
#527
