### ISSUE TITLE
Steam bot bug

### ISSUE THREAD

**Issue by farmor123** [Jessecar96/SteamBot#823]
Log says
[Csgoduckpot bot 2 2015-10-10 23:32:52] INFO: TradeOffer notification
Then does nothing

**Comment by scholtzm** [comment]
You are using API key which is not bound to bot's account.

**Comment by farmor123** [comment]
im actually using the bots api but its connected to localhost does it make any difference depending on the site i've put in to get the api key?

**Comment by scholtzm** [comment]
Site does not matter. But you need to use API key which is registered to bot's particular account.

**Comment by farmor123** [comment]
Just remembered this program is a new device so i got a 7 day trade ban right?

**Comment by scholtzm** [comment]
That would cause problems while accepting/sending. `OnNewTradeOffer` should still run.

**Comment by farmor123** [comment]
how do i know if it still runs`?

**Comment by scholtzm** [comment]
In that case,  #427 and #527. This is an issue tracker, not help desk I'm afraid.
