### ISSUE TITLE
SteamBot not starting

### ISSUE THREAD

**Issue by OMGGDOG** [Jessecar96/SteamBot#824]
root@sd-35551:/usr/local/lib# mono SteamBot.exe
* Assertion at domain.c:724, condition `mono_defaults.runtimetype_class != 0' not met

Native stacktrace:

        mono() [0x49d357]
        /lib/x86_64-linux-gnu/libpthread.so.0(+0xfcb0) [0x7f20db146cb0]
        /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x35) [0x7f20dadaf0d5]
        /lib/x86_64-linux-gnu/libc.so.6(abort+0x17b) [0x7f20dadb283b]
        mono() [0x62c22f]
        mono() [0x62c019]
        mono() [0x62c17d]
        mono() [0x59f5fd]
        mono() [0x424d5e]
        mono(mono_main+0x2e4) [0x4707b4]
        /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed) [0x7f20dad9a76d]
        mono() [0x41f7dd]

Debug info from gdb:

Mono support loaded.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7f20da3ff700 (LWP 22913)]
0x00007f20db14688d in waitpid () from /lib/x86_64-linux-gnu/libpthread.so.0
  Id   Target Id         Frame
  2    Thread 0x7f20da3ff700 (LWP 22913) "mono" 0x00007f20db142d84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
* 1    Thread 0x7f20dbc5f780 (LWP 22912) "mono" 0x00007f20db14688d in waitpid () from /lib/x86_64-linux-gnu/libpthread.so.0

Thread 2 (Thread 0x7f20da3ff700 (LWP 22913)):
#0  0x00007f20db142d84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00000000005fa03c in thread_func (thread_data=0x0) at sgen-thread-pool.c:118
#2  0x00007f20db13ee9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007f20dae6c38d in clone () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7f20dbc5f780 (LWP 22912)):
#0  0x00007f20db14688d in waitpid () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000000000049d401 in mono_handle_native_sigsegv (signal=<optimized out>, ctx=<optimized out>, info=<optimized out>) at mini-exceptions.c:2233
#2  <signal handler called>
#3  0x00007f20dadaf0d5 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007f20dadb283b in abort () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x000000000062c22f in monoeg_log_default_handler (log_domain=0x0, log_level=G_LOG_LEVEL_ERROR, message=0x1edc450 "* Assertion at domain.c:724, condition `mono_defaults.runtimetype_class != 0' not met\n", unused_data=0x0) at goutput.c:233
#6  0x000000000062c019 in monoeg_g_logv (log_domain=0x0, log_level=G_LOG_LEVEL_ERROR, format=0x638f30 "* Assertion at %s:%d, condition `%s' not met\n", args=0x7ffe827678a8) at goutput.c:113
#7  0x000000000062c17d in monoeg_assertion_message (format=0x638f30 "* Assertion at %s:%d, condition `%s' not met\n") at goutput.c:133
#8  0x000000000059f5fd in mono_init_internal (filename=0x7ffe827688ce "SteamBot.exe", exe_filename=<optimized out>, runtime_version=<optimized out>) at domain.c:724
#9  0x0000000000424d5e in mini_init (filename=0x7ffe827688ce "SteamBot.exe", runtime_version=0x0) at mini-runtime.c:3158
#10 0x00000000004707b4 in mono_main (argc=2, argv=0x7ffe82767cc8) at driver.c:1951
#11 0x00007f20dad9a76d in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#12 0x000000000041f7dd in _start ()

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

I get this and i dont know what to do can you help?

**Comment by scholtzm** [comment]
Most likely an issue with your mono installation.

**Comment by OMGGDOG** [comment]
How can i redo it? Just by removing all files?

**Comment by scholtzm** [comment]
Check out #427 and post there.

**Comment by OMGGDOG** [comment]
I'm using the one you run on your own PC and it works there.
