### ISSUE TITLE
Getting problems when opening the SteamBot.exe after compiling

### ISSUE THREAD

**Issue by lowheartrate** [Jessecar96/SteamBot#828]
After I compile the sourcecode and open up the SteamBot.exe to run the bot it gives me error saying *ERROR: Login Error: AccounterLogonDenied* although in the settings file I have everything configured correctly to the steam account. After that error it then shows: *INTERFACE: This account is SteamGuard enabled. Enter the code via the 'auth' command.* - Can somebody show me an example of the code / command that I need to use in order to do this? The example in the repo didn't make much sense to me really ( I have also used the help command to try and figure it out but cannot do so ).

Best regards,
Codi

**Comment by scholtzm** [comment]
Wiki: https://github.com/Jessecar96/SteamBot/wiki/Usage-Guide

**Comment by lowheartrate** [comment]
As I said above 

> The example in the repo didn't make much sense to me really ( I have also used the help command to try and figure it out but cannot do so ).

**Comment by FrozenHaxor** [comment]
Huh? That wiki link @scholtzm posted shows you exactly how to use the auth command.

**Comment by lowheartrate** [comment]
I notice that it explains to me how to do but I need help actually using the command. What is the *zero-based-index* and where do I get my SteamGuard code from?

**Comment by lowheartrate** [comment]
Fixed this problem - Ticket can be closed.
