### ISSUE TITLE
SteamBot instantly declines all trade offers

### ISSUE THREAD

**Issue by lowheartrate** [Jessecar96/SteamBot#829]
As soon as someone sends the steamBot a trade offer it instantly gets declined and doesn't get put into the website at all. No errors show up and nothing in the console that shows up - Any ideas!?

**Comment by SephirothSG** [comment]
This is more than likely an issue with your code. #427 #527 or contact whoever wrote your userhandler.

**Comment by BlueRaja** [comment]
You need to wait 15 days after logging in from a new device to make a trade.  This is a Steam policy to prevent fraud, there's no way to get around it.

**Comment by PVandenheede** [comment]
Isn't it 7 days?

**Comment by scholtzm** [comment]
Yes, I believe it's 15 days for fresh accounts and 7 days for new device. Either way, he won't be able to accept trade offers if he started his bot just yesterday.
