### ISSUE TITLE
SteamBot's CtrlHandler might be using incorrect types

### ISSUE THREAD

**Issue by WildCard65** [Jessecar96/SteamBot#830]
After going through the c++ version of Window's SetConsoleCtrlHandler, the method it takes has the following signature:
typedef
BOOL
(WINAPI *PHANDLER_ROUTINE)(
    _In_ DWORD CtrlType
    );

Where BOOL = int
and DWORD = unsigned long

but in SteamBot, the following types is used in the matching delegate:
bool instead of int
Enum instead of unsigned long

IDK how well C#'s marshal stuff is going to translate between the api well.

**Comment by BlueRaja** [comment]
http://blogs.msdn.com/b/jaredpar/archive/2008/10/14/pinvoke-and-bool-or-should-i-say-bool.aspx
You raise some strange issues sometimes WildCard :)

**Comment by WildCard65** [comment]
And the enum, does that get translated to unsigned long?

**Comment by BlueRaja** [comment]
WinAPI `DWORD` is a 32-bit type _(in C++, `unsigned long` means different things on different systems, which is why the `typedef` exists to begin with)_.  The default types for `enum`s in C# is `int`, which is 32-bit.  So yes, it will work fine.
