### ISSUE TITLE
Virus Warning During Compile

### ISSUE THREAD

**Issue by gunwin100** [Jessecar96/SteamBot#831]
I try to to compile Jessecar96 branch of steambot and AVG pops up a virus warning declaring that there is a trojan horse in the steamtrade.dll file.
Can anyone confirm this is a false positive?  Is someone messing around in the commits?  Am I the only one getting this warning?

**Comment by Darksleep** [comment]
i am not having any of this i just compiled this on one of my server it fine just false positive AVG not very good

**Comment by scholtzm** [comment]
If you downloaded directly from GitHub, it's false positive. Long time ago, someone used part of SteamBot in their phishing tool and it got picked up by couple A/V's unfortunately.

**Comment by BlueRaja** [comment]
#759 #763 #769
