### ISSUE TITLE
Configuration file does not exist or is corrupt.

### ISSUE THREAD

**Issue by son1cman** [Jessecar96/SteamBot#835]
The file (settings.json) and the .exe are on the same directory.

**Comment by scholtzm** [comment]
#427 & #527 

The error is pretty clear though. Either the file does not exist or it's invalid.

**Comment by son1cman** [comment]
i debugged using breaking points on Visual Studio, the line     if (!File.Exists(configFile))
                return false; 
on BotManage.cs return false, im out of ideas.

**Comment by son1cman** [comment]
I found the error, my security settings was making SteamBot.exe not do anything. Sorry for postign this here Jesse, keep up the good work.
