### ISSUE TITLE
Steam bot starting but not accepting offers

### ISSUE THREAD

**Issue by OMGGDOG** [Jessecar96/SteamBot#836]
So i was testing my bot and it doesn't seem to accept my offers it doesn't come with errors and i have disabled email verification thing.
Here's a screenshot:
http://prntscr.com/90uoof

And i also have a issue with the ip thingy.

**Comment by waylaidwanderer** [comment]
This repo is for SteamBot, a project written in C#. Yours is node-steam-tradeoffers.
