### ISSUE TITLE
Auth Help

### ISSUE THREAD

**Issue by romanzdan** [Jessecar96/SteamBot#837]
http://prntscr.com/90wg71

ERROR: InvalidLoginAuthCode
INTERFACE: The Given SteamGuard Code Was Invalid.
Try Again Using Auth Command

I am sure code is right.
Thanks.

**Comment by FrozenHaxor** [comment]
https://github.com/Jessecar96/SteamBot/wiki/Usage-Guide

**Comment by romanzdan** [comment]
what do you mean?
auth 2X85K -- is it wrong?

**Comment by drew73197** [comment]
Assuming that's the first and only bot it would be auth 0=2X85K

**Comment by romanzdan** [comment]
Not working =( http://prntscr.com/90ycax

**Comment by drew73197** [comment]
Try it again maybe? As far as I'm aware that's how you do it.

**Comment by romanzdan** [comment]
Nothing... http://prntscr.com/90yhhy

**Comment by drew73197** [comment]
That bash script you're running check.sh what exactly is it doing when it runs the bots? Is it just executing the bot or what?

**Comment by romanzdan** [comment]
Yes " /opt/mono/bin/mono ./SteamBot.exe bot "

**Comment by drew73197** [comment]
I just noticed you were putting 1 instead of 0 on the auth that might be your issue and if not then I have no idea.

**Comment by romanzdan** [comment]
Nope, http://prntscr.com/90ylni 
Bot work on my 1 server, but on 2 server i've this issue.

**Comment by scholtzm** [comment]
#427 & #527 

Lot's of us are getting e-mail notifications. Usage questions do not belong here.

**Comment by romanzdan** [comment]
Help me pls somebody
