### ISSUE TITLE
String parsing inside of SendTradeMessage is a little weird

### ISSUE THREAD

**Issue by Mates1500** [Jessecar96/SteamBot#838]
```c#
float thisMarketVal = MarketValue.GetMarketValue(tmpDescription.market_hash_name);
SendTradeMessage("{0} added to the trade, estimated value is ${1}", tmpDescription.market_hash_name, thisMarketVal);
SendTradeMessage("{0} has been added to the trade, estimated value equals to ${1}", tmpDescription.market_hash_name, thisMarketVal);
```

**MarketValue** is my own static class that pulls down the median value of a CS:GO item on the market

This results in
```
Desert Eagle | Urban Rubble (Field-Tested) added to the trade, estimated value is $0.1
Desert Eagle | Urban Rubble (Field-Tested) has been added to the trade, estimated value equals to $0
```
The value in the **first** message **is shown as intended**, **not in the second** message, though.

Why do I get different results despite giving the string the exact same arguments in the same order?
I'm not exactly sure, but I think there's something shady going on inside of the part of SendTradeMessage() that parses the string.

**Comment by BlueRaja** [comment]
You are probably hitting the maximum message length

**Comment by scholtzm** [comment]
@BlueRaja is correct. The second string is exactly 100 chars long which is the limit for trade message.

**Comment by Mates1500** [comment]
Oh, I'm an idiot for not realizing this.
I guess the console could still output a warning in case this happens, I'll try and create a pull request for that when I get home.

**Comment by bartico6** [comment]
The solution to outputting a warning would be checking the string length on the bot's side, since steam just cuts the string @ the 100 char point and sends the message without additional characters.

**Comment by BlueRaja** [comment]
@bartico6 #839
