### ISSUE TITLE
Countdown Freez.

### ISSUE THREAD

**Issue by T1mae** [Jessecar96/SteamBot#843]
I set up the Homepage like in the Readme files.
Also the created the Bot with VE. Created Solution with nugget etc.
Thought everything is fine, but when a friend & i tested the page nothing happend.
We both logged in tradet with the bot. The bot expepted the trade and wrote the items in the SQL.
The Items & our Usernames were shown on the Page but the Timer didnt started.
Tried with different items all above 1$ but the timer never started.
Maybe you have a clue.
Homepage :  www.jokersgame.com

Thanks for help and best regards Tim

**Comment by T1mae** [comment]
*accepted the trade ... sorry for my bad english

**Comment by scholtzm** [comment]
This is an issue tracker, not a help desk. Plus your question is not even related to this project.

**Comment by T1mae** [comment]
Oh gosh. Sry yes  was on fault project ... WinBig is the right project which is related to Jessecar96... sorry
