### ISSUE TITLE
Bot crash when trade offer sent

### ISSUE THREAD

**Issue by Koudal222** [Jessecar96/SteamBot#845]
Hello, I'm want to use the SteamBot for my CSGO gamble site!
You can see the error here. It says something with Jordan Turley but I've already edited that, but it keeps saying that.
https://gyazo.com/d22c473aabc4af0ad5cf04c3c3cf150b
Can I maybe code the password into the DepositTradeOfferUserHandler script?

**Comment by scholtzm** [comment]
This is not a SteamBot issue.

cc @BlueRaja

**Comment by Koudal222** [comment]
@scholtzm, what can it be then? :)

**Comment by TheAnthonyNL** [comment]
well in the handler there are lines starting with : string pass =, find these and hardcode your password.

**Comment by Koudal222** [comment]
@TheAnthonyNL , thank you for your response :+1: Im not a good coder, so can you maybe help me? :)

**Comment by BlueRaja** [comment]
#427 #527
