### ISSUE TITLE
Mono error

### ISSUE THREAD

**Issue by krysti500** [Jessecar96/SteamBot#848]
mono SteamBot.exe
* Assertion at domain.c:722, condition `mono_defaults.runtimetype_class != 0' not met

Native stacktrace:

        mono() [0x49fd8a]
        /lib/x86_64-linux-gnu/libpthread.so.0(+0xf0a0) [0x7f36b8fa30a0]
        /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x35) [0x7f36b8a25165]
        /lib/x86_64-linux-gnu/libc.so.6(abort+0x180) [0x7f36b8a283e0]
        mono() [0x62c18e]
        mono() [0x62bf7b]
        mono() [0x62c0dc]
        mono() [0x59dc4b]
        mono() [0x4262de]
        mono(mono_main+0x367) [0x473697]
        /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfd) [0x7f36b8a11ead]
        mono() [0x420e29]

Debug info from gdb:

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

Aborted

**Comment by Jessecar96** [comment]
"This usually indicates a fatal error in the mono runtime or one of the native libraries"
Doesn't seem to be SteamBot related.
