### ISSUE TITLE
Error when pot is max

### ISSUE THREAD

**Issue by Xeroner** [Jessecar96/SteamBot#851]
Please help

[TestBot 2015-11-29 13:54:00] ERROR: System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
w SteamBot.DepositTradeOfferUserHandler.OnNewTradeOffer(TradeOffer offer) w c:\Users\Xeroner\Desktop\CSGOWinBig-SteamBot-master\SteamBot\DepositTradeOfferUserHandler.cs:wiersz 217
w SteamBot.Bot.TradeOfferRouter(TradeOffer offer) w c:\Users\Xeroner\Desktop\CSGOWinBig-SteamBot-master\SteamBot\Bot.cs:wiersz 846
w SteamTrade.TradeOffer.TradeOfferManager.SendOfferToHandler(Offer offer) w c:\Users\Xeroner\Desktop\CSGOWinBig-SteamBot-master\SteamTrade\TradeOffer\TradeOfferManager.cs:wiersz 142
w SteamTrade.TradeOffer.TradeOfferManager.GetTradeOffersSince(Int32 unixTimeStamp) w c:\Users\Xeroner\Desktop\CSGOWinBig-SteamBot-master\SteamTrade\TradeOffer\TradeOfferManager.cs:wiersz 87
w SteamTrade.TradeOffer.TradeOfferManager.GetOffers() w c:\Users\Xeroner\Desktop\CSGOWinBig-SteamBot-master\SteamTrade\TradeOffer\TradeOfferManager.cs:wiersz 113
w SteamBot.Bot.b__10(NotificationCallback callback) w c:\Users\Xeroner\Desktop\CSGOWinBig-SteamBot-master\SteamBot\Bot.cs:wiersz 685
w SteamKit2.CallbackMsgExtensions.HandleT
w SteamBot.Bot.HandleSteamMessage(ICallbackMsg msg) w c:\Users\Xeroner\Desktop\CSGOWinBig-SteamBot-master\SteamBot\Bot.cs:wiersz 672
w SteamBot.Bot.BackgroundWorkerOnDoWork(Object sender, DoWorkEventArgs doWorkEventArgs) w c:\Users\Xeroner\Desktop\CSGOWinBig-SteamBot-master\SteamBot\Bot.cs:wiersz 941

[TestBot 2015-11-29 13:54:00] WARN: Restarting bot...

**Comment by AleksaSavic3** [comment]
How is this a SteamBot issue? You probably changed something in the code. Report this in the  appropriate repository.

**Comment by Xeroner** [comment]
No it's original code

**Comment by AleksaSavic3** [comment]
#427 #527

**Comment by BlueRaja** [comment]
[CSGOWinBig-SteamBot](https://github.com/ztizzlegaming/CSGOWinBig-SteamBot) has been massively altered from the original SteamBot.  You're posting on the wrong project.
