### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Apoloser** [Jessecar96/SteamBot#859]
After configuring bot, getting error
[Bot #1 2015-12-04 23:59:24] ERROR: Login Error: AccountLogonDeniedNeedTwoFactorCode
auth 0-code not helps. Whats the problem?

**Comment by Jessecar96** [comment]
Pull request #855 fixes this.

**Comment by Apoloser** [comment]
Updated sources. Another one error
[Bot #1 2015-12-05 00:59:32] ERROR: Login Error: AccountLogonDeniedNeedTwoFactorCode
[Bot  #1 2015-12-05 00:59:32] ERROR: Failed to generate 2FA code. Make sure you have linked the authenticator via SteamBot.

**Comment by waylaidwanderer** [comment]
You need to link the authenticator using SteamBot. Make sure you don't already have a mobile authenticator added.

**Comment by Apoloser** [comment]
Entering auth 0-[steam-protection-code] and nothing happens...

**Comment by speed-str** [comment]
@waylaidwanderer How can i do that ? i've tried multiple times in the console still no luck. or do i have to edit the handler ?

**Comment by waylaidwanderer** [comment]
`exec [bot index] linkauth`

**Comment by speed-str** [comment]
@waylaidwanderer i've tried that but having issues. Attached my screenshot. Plus i may want to tell you that i am running the application inside a virtual machine because i cannot run it on my host windows, it just doesn't start i can see process via task manager but no console or anything. without the 2FA, the bot on virtual machine is working just fine.

P.S it seems that the bot is trying to access a path that is on my host windows because i've compiled the steambot on my host windows and the bot is trying to read bot.cs which is on the host windows.
![git](https://cloud.githubusercontent.com/assets/16186409/11936360/140ea740-a82f-11e5-87e1-8cb841010bc9.png)

**Comment by scholtzm** [comment]
The exe file alone is not going to work. You need all the dlls too.

**Comment by speed-str** [comment]
@scholtzm Got it working ! thanks. just needed to copy the dll's thats all

**Comment by SnaBe** [comment]
I get this error when i start up the bot. Where exactly do I find this file, and how do I link it? The account the bot is signed to, has had the mobile auth enabled for 5 days.
![bot error](https://cloud.githubusercontent.com/assets/16469268/12027252/c2ad9af6-adc3-11e5-8943-69fb77d14e61.png)

**Comment by speed-str** [comment]
@SnaBe it seems you've already added a mobile authenticator on that account. Remove that first and then execute this command after starting your bot  "exec [index] linkauth" where index is the index of your bot usually 0 if you have only 1 bot

**Comment by VVILD** [comment]
@speed-str

i get this error after disabling my previous mobile authenticator and writing exec 0 linkauth

ERROR: Error performing mobile login: GeneralFailure

**Comment by hscanlan** [comment]
@waylaidwanderer I have the same error as above ..

I added a phone number to my account via steam - but haven't added a mobile authenticator ( the bot itself ). Used 

exec 0 linkauth

**Comment by Nickthegoatboy** [comment]
@hscanlan Having similar problem to your new one. Have you found a solution?

**Comment by hscanlan** [comment]
Hey @Nickthegoatboy .. I honestly did find a solution - but I don't remember what it was off the top of my head. The project is now over on my end, so I can't be much of a help to you since I don't have the project open :(  I think mine was just a glitch and rerunning the bot fixed it.

Sorry!

**Comment by Nickthegoatboy** [comment]
@hscanlan No worries and thanks for the quick response! I ended up figuring it out - I unlinked the phone number that I had manually linked and ran linkauth and it worked. Thanks for the quick response and sorry about the date, when I first glanced at it I thought it said February 2017 not 2016.
