### ISSUE TITLE
Bot can't accept trade with outgoing items in offer with "Trade confirmations" enabled

### ISSUE THREAD

**Issue by vanqaaa** [Jessecar96/SteamBot#863]
I'm using bot to accept all trade offers from all users, with slighty modified `TradeOfferUserHandler.cs` (http://pastebin.com/ve0weLnA) So when offer comes for bot items bot accepting in once, next offers just ignored and if i open `SteamDesktopAuthenticator` it's showing pending "Trade confirmation" so actually bot trying to accept but not confirm it. Sorry for my English

**UP.** FIX [issuecomment-166022439](https://github.com/Jessecar96/SteamBot/issues/863#issuecomment-166022439)

To reproduce:
Bot needs to be enabled "Trade confirmations" (In your Steam community profile private settings)

1. Shutdown bot, send to bot offline trade with only taking items from bot 
2. Start bot (first time bot will accept offer successfuly and show web error http://pastebin.com/raw.php?i=8gCCfsR6 maybe this is a problem?)

 ``` [Bot 2015-12-06 00:51:03] INFO: They want 1 of my items. ```
``` [Bot 2015-12-06 00:51:03] INFO: And I will get 0 of their items. ```
``` [Bot 2015-12-06 00:51:07] SUCCESS: Confirmed Trade with xxxx. (Confirmation ID #xxxx) ```

3. Send to bot same offer again and bot will trying to accept offer, but can not confirm new "Trade confirmation" and stuck on this:

  ``` [Bot 2015-12-06 00:52:23] INFO: They want 1 of my items.```
  ``` [Bot 2015-12-06 00:52:23] INFO: And I will get 0 of their items.```

>now if you open SteamDesktopAuthenticator it's showing pending "Trade confirmation"

4 . If you immediately restart bot, offer will accepted fine now. So you need restart bot everytime to confirm outgoing items from bot. (Offers where only incoming items, accepting fine)

**Comment by Andrijazz** [comment]
Is there a way to get individual trade offer based on confirmation id/key only?

**Comment by scholtzm** [comment]
It's possible and it requires yet another slow HTTP request.

**Comment by Andrijazz** [comment]
Can you send me the url? I can't find it anywhere ...

**Comment by scholtzm** [comment]
The trade offer ID can be retrieved from `https://steamcommunity.com/mobileconf/details/<confID>`.

**Comment by Andrijazz** [comment]
Thanks @scholtzm

**Comment by vanqaaa** [comment]
Any help?

**Comment by Arge** [comment]
I think I've found a temporary fix, offer.Accept() It should be without `if ()`, replace this code:
`string tradeid;`
`if (offer.Accept(out tradeid))`
`{`
`   Bot.AcceptAllMobileTradeConfirmations();`
`   Log.Success("Accepted trade offer successfully : Trade ID: " + tradeid);`
`}`
for this:
`offer.Accept()`
`Bot.AcceptAllMobileTradeConfirmations();`
`Log.Success("Accepted trade offer successfully.);`

**Comment by vanqaaa** [comment]
@Arge Wow Man! Thanks a lot!!! Love you :D

**Comment by scholtzm** [comment]
That piece of code is obviously error-prone.

**Comment by vanqaaa** [comment]
@scholtzm it's a just little errors witch can be fixed when compiling. At least this only one guy who helping here...  Waiting 2 weeks, no one tried help me  :/

**Comment by waylaidwanderer** [comment]
Unfortunately we can't always trust Steam to return `success: true`. Last week I ran into a case where cancelling a trade offer consistently gave an empty response (literally just: `{ response: {} }`) but cancelled the trade still.

**Comment by scholtzm** [comment]
@vanqaaa If `Accept` method returns false even if the trade offer gets accepted, the issue must lie elsewhere. The fix is very short-sighted and will only produce more errors in the future. You can however troubleshoot this properly with a bunch of breakpoints.

**Comment by orik007** [comment]
Your code should not rely on single methods like accept, cancel etc. Always use gettradeoffers and pick result from there.

**Comment by vanqaaa** [comment]
As my bot only accepting offers and fix from @Arge works, issue can be closed. Thanks
