### ISSUE TITLE
SteamWeb.VerifyCookies is missing a CookieContainer parameter

### ISSUE THREAD

**Issue by AleksaSavic3** [Jessecar96/SteamBot#867]
I noticed that VerifyCookies() boolean in SteamWeb(https://github.com/Jessecar96/SteamBot/blob/master/SteamTrade/SteamWeb.cs#L259) is missing a CookieContainer parameter(it is mentioned in XML documentation above it).

Is the XML documentation outdated or CookieContainer parameter should be added?

**Comment by scholtzm** [comment]
Docs are outdated. Cookies were originally stored in the Bot class and SteamWeb was just a static utility class for web requests.

**Comment by AleksaSavic3** [comment]
Thanks.
