### ISSUE TITLE
Determining items assetid after accepted trade offers by partner

### ISSUE THREAD

**Issue by orik007** [Jessecar96/SteamBot#872]
Hey

If bot creates trade offer and partners accepts it, all items assetid are changed.
Is there any way to easy determine this change and get anywhere new asset ids?

I can ofc call getinventory for each accepted trade offer and do some magic with hashmarketname, instanceid and classid etc, but i hope there is a better way.

Its about trade offers not accepted by bot, but accepted by partner. So i dont have tradeId and i cant call trade/{tradeid}/receipt api.

Em I missing something?

**Comment by AleksaSavic3** [comment]
This is an issue tracker, not a helpdesk. I think that this question would be better for reddit.

**Comment by AleksaSavic3** [comment]
See #427.

**Comment by orik007** [comment]
Well, this can be a Issue, cos without this function is bot useless. I know SteamBot can not be used without modification for production environment.
Noone could answer me on reddit.

**Comment by orik007** [comment]
Its by tradeId and receipt btw.
