### ISSUE TITLE
How is the process of confirming a trade on node steam bots?

### ISSUE THREAD

**Issue by danifantom** [Jessecar96/SteamBot#873]
Hey guys, I'm new here but for years I've found a lot of help on this community and I'm really grateful for that.
I have a steam bot coded on node js and I have it already logging in automatically with the generated 2fa code with steam-totp. Now I want to be able to confirm my trades with the generated confirmation code but I'm totally lost about the process. I already have to key to confirm, how Am I supposed to use it? Thank You very much!

**Comment by waylaidwanderer** [comment]
This is the repo for the C# Steam bot project, "SteamBot". You're in the wrong project repo.

**Comment by danifantom** [comment]
Oh, I'm sorry! Like I said I'm new ^^... Really sorry, what should I do? Delete and re-create the post?

**Comment by waylaidwanderer** [comment]
Close this issue and don't bother recreating it, because you're entirely in the wrong place. :(

PS: you may be looking for http://reddit.com/r/SteamBot
