### ISSUE TITLE
CSGO jackpot node steam bot trade offer with the new system escrow ?

### ISSUE THREAD

**Issue by wedzyou** [Jessecar96/SteamBot#879]
Hello,I'm using an node steambot for my gambling site but now with the new stupid steam escrow the trade offer of my bot dosen't work anymore sor i'm asking for your help because i have searching a lot how to fix that but no result

my bot code: http://pastebin.com/9d2HkR10

I Thank You in advance,Have a Nice day

**Comment by BlueRaja** [comment]
This is not the node Steambot repository.
