### ISSUE TITLE
Visual Studio 2010 problem

### ISSUE THREAD

**Issue by patruvlad** [Jessecar96/SteamBot#881]
Hello, I've tried to open the project in visual studio 2010 and i get a error "The selected file is a sollution file, but was created with a newer version of this application and cannot be opened" 

How can i get this to work?

**Comment by Darksleep** [comment]
Really easy it even tell how to fix it newer version so just download newest one see it easy when you google first

**Comment by AleksaSavic3** [comment]
Visual Studio 2013 or higher is needed.
