### ISSUE TITLE
AcceptAllMobileTradeConfirmations for specific trade

### ISSUE THREAD

**Issue by nero08** [Jessecar96/SteamBot#883]
Hi,

It is possible to accept a specific trade ? Because, at this time, the only method in bot is AcceptAllMobileTradeConfirmations(); and this method accept all trade.

Maybe retrieve the tradeofferid with the confID or confKey ?

Thanks in advance.

**Comment by waylaidwanderer** [comment]
As far as I know, confID and confKey doesn't match the tradeofferid.

**Comment by nero08** [comment]
So, how to confirm one specific trade if we can't with this data?

**Comment by waylaidwanderer** [comment]
You can check if the Steam profile name is the same with the confirmation description, but obviously that won't work if you have more than 1 trade offer with the same person, or if two people have the same name. Point is SteamAuth doesn't have the functionality to get you details about a trade yet.

**Comment by nero08** [comment]
It's a big problem...

**Comment by nero08** [comment]
And with the avatarId?

https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/fe/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb.jpg

with: fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb

**Comment by waylaidwanderer** [comment]
This is a Steam limitation, it doesn't provide any data about the trade offer (like id, etc). I'm not sure if you can get any information about the user based on the avatar URL, but again, it obviously won't work if you have more than 1 trade offer with the same person.

**Comment by scholtzm** [comment]
You can retrieve the trade offer ID from `details` page if you have the `confID`. It takes an extra HTTP request for each confirmation to get the trade offer ID.

**Comment by nero08** [comment]
The details page? Could you give me the link or an example?

**Comment by scholtzm** [comment]
`https://steamcommunity.com/mobileconf/details/<confID>`

it requires the same params as confirmation URL - you'll need to generate valid key and all that

**Comment by waylaidwanderer** [comment]
@geel9 Can you add this to SteamAuth?

**Comment by nero08** [comment]
Implementation example:
In SteamGuardAccount.cs
```
public string GetTradeOfferIdFromConfirmation(string confId)
        {
            try
            {
                string url = this.GenerateConfirmationOfferIdURL(confId);

                CookieContainer cookies = new CookieContainer();
                this.Session.AddCookies(cookies);

                string response = SteamWeb.Request(url, "GET", null, cookies);
                var offerResponse = JsonConvert.DeserializeObject<ConfirmationTradeOfferIdResponse>(response);

                Regex offerIdRegex = new Regex("id=\"tradeofferid_([0-9]+)\"");

                //Console.WriteLine(offerIdRegex.IsMatch(offerResponse.Response.Html));
                if (offerResponse == null || !offerResponse.Success || !offerIdRegex.IsMatch(offerResponse.Html))
                    throw new WGTokenInvalidException();


                MatchCollection OfferIdMatch = offerIdRegex.Matches(offerResponse.Html);

                return OfferIdMatch[0].Groups[1].Value;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return "";
            }
            
        }
```

```
public void AcceptAllMobileTradeConfirmations()
        {
            if (SteamGuardAccount == null)
            {
                Log.Warn("Bot account does not have 2FA enabled.");
            }
            else
            {
                SteamGuardAccount.Session.SteamLogin = SteamWeb.Token;
                SteamGuardAccount.Session.SteamLoginSecure = SteamWeb.TokenSecure;
                try
                {
                    foreach (var confirmation in SteamGuardAccount.FetchConfirmations())
                    {
                        string offerId = SteamGuardAccount.GetTradeOfferIdFromConfirmation(confirmation.ConfirmationID);
                        TradeOffer tradeOffer = null;
                        if (TryGetTradeOffer(offerId, out tradeOffer))
                        {
                            if (tradeOffer.IsOurOffer || Bot.BotSteamIds.Contains(tradeOffer.PartnerSteamId))
                            {
                                if (SteamGuardAccount.AcceptConfirmation(confirmation))
                                {
                                    Log.Success("Confirmed {0}. (Confirmation ID #{1})",
                                        confirmation.ConfirmationDescription, confirmation.ConfirmationID);
                                }
                            }
                            else
                            {
                                if (SteamGuardAccount.DenyConfirmation(confirmation))
                                {
                                    Log.Error("Canceled {0}. (Confirmation ID #{1})",
                                        confirmation.ConfirmationDescription, confirmation.ConfirmationID);
                                }
                            }
                        }
                        
                    }
                }
                catch (SteamAuth.SteamGuardAccount.WGTokenInvalidException)
                {
                    Log.Error("Invalid session when trying to fetch trade confirmations.");
                }
            }                        
        }
```

**Comment by waylaidwanderer** [comment]
Wouldn't it be better to add a function to confirm a specific trade offer rather than modifying `AcceptAllMobileTradeConfirmations()`?

**Comment by nero08** [comment]
It's for my bot, so you can do it the way you want it.

**Comment by Andrijazz** [comment]
Hey guys, I keep getting the following exception when I try to fetch trade offers : "Cannot handle redirect from HTTP/HTTPS protocols to other dissimilar ones."
It happens intermittently. Does anybody knows what is the problem?

**Comment by waylaidwanderer** [comment]
@nero08 Where is the code for `GenerateConfirmationOfferIdURL(confId)`?

**Comment by nero08** [comment]
```
public string GenerateConfirmationOfferIdURL(string confID, string tag = "details")
        {
            string endpoint = APIEndpoints.COMMUNITY_BASE + "/mobileconf/details/"+confID+"?";
            string queryString = GenerateConfirmationQueryParams(tag);
            return endpoint + queryString;
        }

        public string GenerateConfirmationQueryParams(string tag)
        {
            long time = TimeAligner.GetSteamTime();
            return "p=" + this.DeviceID + "&a=" + this.Session.SteamID.ToString() + "&k=" + _generateConfirmationHashForTime(time, tag) + "&t=" + time + "&m=android&tag=" + tag;
        }

```

**Comment by waylaidwanderer** [comment]
I figured out the same thing as well. Might need to make a pull request to SteamAuth with this.

**Comment by nero08** [comment]
You can do it if you want

**Comment by BlueRaja** [comment]
What's the use-case for this?  If you want to accept/deny a certain trade, you should do that using the trade/trade-offer methods already available.  Once it gets to the mobile authentication part, it should have already been accepted... right?

**Comment by scholtzm** [comment]
But you can still cancel the confirmation.

**Comment by BlueRaja** [comment]
Right, but I'm saying if you want to cancel it you should cancel it at the "trade (offer) received" stage, not the "trade (offer) has already been accepted by the bot and is just awaiting mobile confirmation" stage

**Comment by BlueRaja** [comment]
~~But what would be the use-case for that?~~

**[Edit]** Actually, nevermind, I just thought of a use-case:

1. Bot has only one non-steam item for sale (such as a Steam key or something).
2. One person buys it, but never does mobile confirmation on it.  Bot doesn't want to bring the item down for sale (that would be easy to DOS attack).  
3. A second person buys the item and mobile-confirms it.  Bot now needs to cancel the first trade.

**Comment by orik007** [comment]
blueRaja:

Case you described has no logic.. 

If one person buys something, he pays money and the item belongs to him. Nevermind if he accepts or not. You should have button to resend bot. 

There is not possible to ddos anything, cos no1 has unlimited funds.

**Comment by BlueRaja** [comment]
I meant buys it with TF2 keys or whatever.  In that case, they haven't actually "paid for it" until the trade is accepted and mobile-confirmed by both parties.

**Comment by scholtzm** [comment]
Why is the possible use case even being discussed? This is a matter of one HTTP call and implementing this is fairly trivial.

**Comment by nero08** [comment]
The problem in my case is that I have several bot that transmit items to each other ( seller , storage , trader ) . For example, if someone proposes a trade offer directly to my bot storage to retrieve an object ( to steal it for example) and while I normally do not allow it , and if I use the " AcceptAllMobileTradeConfirmations " then it will confirm all trades , even the trades that were generated by maize intentioned people.

So my function that I share in my previous post serves to accept unitary trades.

**Comment by geel9** [comment]
I've pushed changes to SteamAuth that allow you to retrieve the trade offer ID associated with a confirmation, but it requires an extra HTTP request for each confirmation.

**Comment by waylaidwanderer** [comment]
Just made a pull request for this based on @geel9's changes.

[SteamTradeOffersBot](https://github.com/waylaidwanderer/SteamTradeOffersBot/) has had this functionality for a while which has been working fine.

**Comment by BlueRaja** [comment]
Completed in #917
