### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by optiix** [Jessecar96/SteamBot#884]
Hello. I have a website that used a fork of jessecars bot. It uses /Steambot/DepositHandler.cs where I set webpage info etc before compiling. Now...

1) How do I implement this "DepositHandler.cs" to your new updated BOT that have this mobile auth and get it to work togehter with the rest fo your new updated files.

2) How do I setup this mobile auth? I dont see any extra line in settings.json and no config file in /SteamAuth/. Can someone please write a guide. I would love to get this working very soon :(

It isnt me that has written the code therefore I know notging about it. I bought it a while ago.. :(
CODE OF DepositHandler.cs --> http://justpaste.it/ppuj

If someone thinks the code is shit, can someone simple implement it for free in the new updated BOT with mobile auth? Becuase I think it has with SQL and so so everything gets inserted correct into the db.. :|

**Comment by BlueRaja** [comment]
#427 #527
