### ISSUE TITLE
Missing reference

### ISSUE THREAD

**Issue by son1cman** [Jessecar96/SteamBot#886]
i just cloned the project, while building its show: Error	8	The type or namespace name 'SteamAuth' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\client\Documents\GitHub\CSGOWinBig-SteamBot\SteamBot\Bot.cs	131	16	ExampleBot
i try build order, remove and readd the reference, even downloading manually the dependecy (the version which steambot is working) and i still getting the message.. is

**Comment by scholtzm** [comment]
> C:\Users\client\Documents\GitHub\CSGOWinBig-SteamBot\

Clearly a different project.

**Comment by son1cman** [comment]
what? the folder is clonned from github... dont get ur point

**Comment by StoneWolf** [comment]
You probably cloned this: https://github.com/ztizzlegaming/CSGOWinBig-SteamBot
While you are posting your issue on this: https://github.com/Jessecar96/SteamBot

Not the same URL, not the same project. You should file an issue on the other GitHub page.

**Comment by son1cman** [comment]
oh you mean the csgowinbig thinkg... its irrelevant, its forked from jesse, im testing both and its the same, my bad, im trying on bot projects
