### ISSUE TITLE
GeneralFailure #878 still persist

### ISSUE THREAD

**Issue by speed-str** [Jessecar96/SteamBot#887]
Still having generalfailure issue after trying to link authentication via "exec [index] linkauth"

Issue #878 still persists

Log:
[(System) 2015-12-22 12:01:26] DEBUG: Sending command "linkauth" to Bot at index 0
[#1 2015-12-22 12:01:29] INTERFACE: Enter Steam Guard code from email (type "input [index] [code]"):
[(System) 2015-12-22 12:01:54] DEBUG: Sending input "XXXXX" to Bot at index 0
[#1 2015-12-22 12:01:56] INFO: Linking mobile authenticator...
[#1 2015-12-22 12:01:57] INTERFACE: Enter phone number with country code, e.g. +1XXXXXXXXXXX (type "input [index] [number]"):
[(System) 2015-12-22 12:02:28] DEBUG: Sending input "+92XXXXXXXXXX" to Bot at index 0
[#1 2015-12-22 12:02:29] ERROR: Error adding authenticator: GeneralFailure

**Comment by bartico6** [comment]
Steam has been having problems recently, I'd say it's some sort of retarded "Server not responding" issue. Just try it again tomorrow or something.

**Comment by speed-str** [comment]
@bartico6 still nothing. maybe it could be a cause of json assembly because when ever i fetch a new release of this git i have to reinstall the component Update-Package –reinstall Newtonsoft.Json in the nuget console. i've been encountering problems with it lately because when i switch the bot to 6.0.0.0 everything runs fine except the steamAuth which throws error that json 7 could not be found and when i switch the bot to json 7, i can't even start the bot which throws error "version 6 could not be found". Any ideas ?

**Comment by scholtzm** [comment]
You have to install both packages. Don't try to replace one another.

**Comment by speed-str** [comment]
@scholtzm well thats how i get the generalFailure error :P installing both packages works fine but can't link authenticator

**Comment by scholtzm** [comment]
The "GeneralFailure" error has nothing to do with NuGet packages though.

**Comment by speed-str** [comment]
@scholtzm yep ! let me try another phone number to workaround this issue

**Comment by speed-str** [comment]
Still getting the same error

**Comment by scholtzm** [comment]
Since you have direct access to SteamAuth source, why don't you just trace the point of failure using debugger? GeneralFailure does not mean anything so there's not much anyone can do for you.

**Comment by speed-str** [comment]
@scholtzm sure can do that. linked to issue 878 for better reviews
