### ISSUE TITLE
Suggestin

### ISSUE THREAD

**Issue by BananaJoystick** [Jessecar96/SteamBot#890]
It's pretty cool that you can have several accounts with one .exe file now, instead of one per user. But I have rather random account usernames, would it be possible to rename them? Maybe add image or something. User-friendly.

**Comment by BlueRaja** [comment]
What are you talking about?  There is no GUI..

**Comment by Jessecar96** [comment]
He's probably talking about https://github.com/Jessecar96/SteamDesktopAuthenticator

**Comment by BananaJoystick** [comment]
Yes, I did. I don't understand Github very well, no idea how to properly use this thing
