### ISSUE TITLE
Steam API Error. Bot crashes.

### ISSUE THREAD

**Issue by TheRod1990** [Jessecar96/SteamBot#891]
Hi, i need some help with this. Everytime the Bot is doing something it uses the doWebWithCatch function in the TradeOfferHandlers, which gives me a tons of API Errors. Like this one: 

    [[CSGOLagoon.com] 2015-12-28 03:59:16] SUCCESS: Offer accepted from STEAM_0:0:119356017
    [[CSGOLagoon.com] 2015-12-28 03:59:19] ERROR: Steam API error encountered. Trying again.    Tries: 1

Sometimes, when the Bot send an offer to the winner, the bot crashes and is ending in an endless error pinging of Steam API Errors and wont send any offer the winner.

**Comment by ESKAYEM** [comment]
got the same error... dont really what to do :/

**Comment by BlueRaja** [comment]
This is not a SteamBot error.  I think you want https://github.com/ztizzlegaming/CSGOWinBig

**Comment by TheRod1990** [comment]
Thanks man!
