### ISSUE TITLE
Reasons Trades not confirmed?

### ISSUE THREAD

**Issue by ThereWasADream** [Jessecar96/SteamBot#894]
Hey everyone, I'm sure you've noticed the mobile confirmations don't always work. I've simply made my bot accept confirmations often in case some get missed, but I think some are simply not getting confirmed *ever*. Any particular reason for this? Is it a Steam issue? Can confirmations get lost? Thanks!

**Comment by scholtzm** [comment]
Trade confirmations sometimes do not appear. Not sure why but it's ~5% of all trades.

**Comment by ThereWasADream** [comment]
OK, well I'm glad that at the very least I'm not the only one able to figure out why the don't get retrieved. I thought maybe their might be some kind of HTML thing I didn't understand that could help me with confirmations. Unless their is.

**Comment by scholtzm** [comment]
They just don't appear. Ever. _It's a Steam thing._
