### ISSUE TITLE
Error when trying to link authenticator

### ISSUE THREAD

**Issue by Glavatar** [Jessecar96/SteamBot#896]
Hey,

So, whenever I type "exec 0 linkauth" I get this error: http://prntscr.com/9m6s18
I even deleted my antivirus since I thought that antivirus was causing this problem but I still get this error. Linking authenticator with waylaidwanderer's trade offer bot is working fine, but I can't manage to link authenticator with this particular bot. Any clue on how to fix this ?

Thanks in advance.

**Comment by RafalNiewinski** [comment]
Do you have latest version from repository?
If you answer says yes try to remove newtonsoft.json from references and add it again from NuGet, then recompile your solution.

**Comment by BlueRaja** [comment]
Does https://github.com/Jessecar96/SteamBot/pull/913 fix it?

**Comment by Glavatar** [comment]
#913 Fixed it.
Thanks :)
