### ISSUE TITLE
OnTradeOfferReceived doesn't work

### ISSUE THREAD

**Issue by CopyAndPaste1337** [Jessecar96/SteamBot#898]
Hi there.

I was using SteamTradeOffersBot (which is based on this) from Joel (waylaidwanderer) and i noticed OnTradeOfferReceived doesn't react if there is a trade available from another user. As I saw OnTradeOfferReceived is trying to get called in CheckPendingTradeOffers, its going through some ifs, but it still doesn't call it.

Could somebody help me with that?

**Comment by waylaidwanderer** [comment]
Wrong repo.

https://github.com/waylaidwanderer/SteamTradeOffersBot/

**Comment by CopyAndPaste1337** [comment]
Thanks for the info.
