### ISSUE TITLE
Steam bot crashes after trade accepted and fails to send trade.

### ISSUE THREAD

**Issue by sword134** [Jessecar96/SteamBot#900]
As the title says everytime i trade with my bot on my website i get this error: https://gyazo.com/89f39fa0c02e63bcea2b1be818770151

It does deposit the skins though but on end of the round it crashes when trying to return skins to winner.

**Comment by waylaidwanderer** [comment]
Okay, first of all, this repo is for **SteamBot**, which is a *C#* framework. Your screenshot shows a *node.js* bot.

Secondly, this place is for issues with the framework itself, not with your own personal bot code.
