### ISSUE TITLE
The namespace "NewtonSoft" and "JsonProperty" could not be found.

### ISSUE THREAD

**Issue by Racskobence** [Jessecar96/SteamBot#901]
I get like 30 of each of them every time I build it and I also have C:\Users\Me\Documents\SteamBot\SteamAuth\SteamAuth\Bin\Debug\SteamAuth.dll could not be found. If you could solve this error I would really appreciate it. I cloned from Jessecar96 with git clone --recursive git://github.com/Jesseca96/SteamBot
I also tried to make NuGet Automatically download packages and also tried manually download photobuf-net, SteamKit2 and Newtonsoft.Json. Didnt work.

**Comment by debugger-perm** [comment]
Check target framework

2016-01-08 13:36 GMT+05:00 Racskobence <notifications@github.com>:

**Comment by Racskobence** [comment]
How can I do that? Im using MSVS2015 With NuGet for VS2015.... What should I exactly do??

**Comment by alfiecee** [comment]
Currently having the same issue. Any help would be much appreciated.

**Comment by scholtzm** [comment]
Manually removing and adding Newtonsoft.Json dependency to SteamAuth fixed the issue on my end - missing Newtonsoft.Json dependency. However, I still think that the project should be just buildable after cloning (incl. the dependencies).

@BlueRaja what do you think?

**Comment by alfiecee** [comment]
@scholtzm How would I go about doing that? Not quite sure I understand what you mean.

**Comment by Racskobence** [comment]
Me too... Can you explain me how to exactly build it when it shows me 51 errors including missing SteamAuth.dll, namespace Newtonsoft and JsonProperty? I cannot build it.... I cloned the SteamBot from Jessecar96 with the command git clone --recursive git://github.com/jessecar96/SteamBot in the git shell. That is what I knew how to do..... Any other tips, @debugger-perm  @alfiecee  @scholtzm ???

**Comment by BlueRaja** [comment]
@sholtzm Ultimately someone _(preferably the original author)_ needs to publish SteamAuth to nuget so we don't need to use submodules.

**Comment by CmDeRdarkhell** [comment]
Oh I thought it was just me,
I'll try to do what debugger-perm said.

**Comment by alfiecee** [comment]
@CmDeRdarkhell Can you explain how you did what @scholtzm said? 
I still can't seem to get it working.

**Comment by scholtzm** [comment]
@BlueRaja Yeah, but even if it is a submodule, shouldn't the project be buildable straight away? If I clone the project and try to build it, every dependency is properly downloaded except for SteamAuth's JSON dep.

@CmDeRdarkhell You need to add SteamTrade.dll to your anti-virus' whitelist. Unfortunately, it has been previously used by phishers.

**Comment by Racskobence** [comment]
I've fixed it by going on th project, right clicking on 'References' and going on 'Manage NuGet packages' and updating 'em all. I has fixed my errors, but still getting 15 more... Looks like 'Severity	Code	Description	Project	File	Line
Error	CS1061	'ICallbackMsg' does not contain a definition for 'Handle' and no extension method 'Handle' accepting a first argument of type 'ICallbackMsg' could be found (are you missing a using directive or an assembly reference?)	ExampleBot	C:\Users\Me\Documents\GitHub\SteamBot\SteamBot\Bot.cs	715'
Opening a new Issue for that.

**Comment by CmDeRdarkhell** [comment]
@scholtzm I figured that out by googling the problem, thanks for the advise anyways.

Does anyone know what this problem is after compiling?
this is 1 seconds after opening the bot http://puu.sh/mplpF/95b5fc9f90.png

**Comment by alfiecee** [comment]
@Racskobence THANK YOU THANK YOU THANK YOU
