### ISSUE TITLE
ICallbackMsg error

### ISSUE THREAD

**Issue by Racskobence** [Jessecar96/SteamBot#902]
I get this error all the time I try to build the SteamBot project. I dont know what to do know. Can you help me? My error:
Severity	Code	Description	Project	File	Line
Error	CS1061	'ICallbackMsg' does not contain a definition for 'Handle' and no extension method 'Handle' accepting a first argument of type 'ICallbackMsg' could be found (are you missing a using directive or an assembly reference?)	ExampleBot	C:\Users\Me\Documents\GitHub\SteamBot\SteamBot\Bot.cs	715

**Comment by scholtzm** [comment]
You installed incorrect SteamKit version from NuGet. You'll need 1.6.2.

https://github.com/Jessecar96/SteamBot/blob/master/SteamBot/packages.config#L5
