### ISSUE TITLE
Trojan Warning Atros2.BVRU

### ISSUE THREAD

**Issue by andrekgb** [Jessecar96/SteamBot#906]
Hi and Thanks for the Bot.

I downloaded the project and when trying to compile it, in Windows 7 and Visual Studio 2015, AVG antivirus gives me a trojan warning on the SteamTrade.dll file saying that it contains the Atros2.BVRU trojan.

Do you have any information about it?

![trojan](https://cloud.githubusercontent.com/assets/6100485/12292206/abd1e2b8-b9d2-11e5-8113-e3dde53d794e.png)

**Comment by scholtzm** [comment]
Yes, it's false positive. Some people used parts of SteamBot for phishing in the past.

**Comment by BlueRaja** [comment]
Please search before posting issues

#759 #763 #769 #770 #831 #832
