### ISSUE TITLE
Bot doesn't start

### ISSUE THREAD

**Issue by Sneaky2x** [Jessecar96/SteamBot#907]
My bot just stays like this, he used to work but now I don't know why it stopped working :/

![image](https://cloud.githubusercontent.com/assets/15880984/12373912/f133443e-bc82-11e5-80d9-5cfe70bdaa03.png)

even when i type the commands given on help he doesn't do anything, please help :/

and debugging says this....

![image](https://cloud.githubusercontent.com/assets/15880984/12374043/bfe7816a-bc87-11e5-87c6-604a5e2994c3.png)

**Comment by peterwilli** [comment]
Do you by any chance have a peer blocker like peerguardian running? I have that and got into the same problem, had to disable it to continue using steambot.

**Comment by Sneaky2x** [comment]
No I don't think I have a peer blocker on my computer, the one thing that comes to my mind is that I installed Win8.1 latelly and previously on win7 the bot was fine, so since I had to reinstall everything maybe something on my pc is missing? :/ the solution compiles fine though, no erros or warnings, just doesnt work, configs are fine and all :/

**Comment by Savikas** [comment]
Found fix for it: Turn off your firewall on PC
