### ISSUE TITLE
There was and error sending an offer (50)

### ISSUE THREAD

**Issue by glukamin** [Jessecar96/SteamBot#908]
I read somewhere that this happens in case bot is sending to many offers. How can I fix this and avoid from happening?

**Comment by orik007** [comment]
Do not send too many offers

**Comment by waylaidwanderer** [comment]
You have only have a maximum of 30 sent trade offers, and a maximum of 5 per person.

**Comment by glukamin** [comment]
Does that mean 5 per person until they are accepted or declined?

**Comment by scholtzm** [comment]
5 active.

**Comment by glukamin** [comment]
Thanks guys.
