### ISSUE TITLE
Is my improvement to Bot.AcceptAllMobileTradeConfirmations() wanted/needed?

### ISSUE THREAD

**Issue by ThereWasADream** [Jessecar96/SteamBot#911]
See link at bottom. While trying a merger of /u/waylaidwanderer 's TradeOffersBot repo and vanilla SteamBot, I found a way to avoid some of the session and cookie issues that sometimes make this confirmation method fail. Waylaid made a commit about the same idea except his was better of course since I'm a novice. However I prefer my own method as it has a more aggressive method of ensuring every trade is confirmed.

Assuming
A. I am not the only one who has had this issue and
B. You all are interested

I am considering making a small pull request to update the method. It's a combination of the method I put together and a slightly different method /u/waylaidwanderer added to his own repo last night. Assuming he has no objections I think it'd be wrong not to share.

Here it is in my own repo: https://github.com/ThereWasADream/KeyBot/blob/master/SteamBot/Bot.cs#L1284

**Comment by BlueRaja** [comment]
? This is not a pull-request.  To create a pull-request, go to the pull-request tab in the top and click 'new pull request'.

You will probably want to create a new branch, so you can continue to add things to your master-branch while the PR is open.

**Comment by waylaidwanderer** [comment]
I fixed an issue with that code 2 commits ago by the way: https://github.com/waylaidwanderer/SteamTradeOffersBot/commits/SteamTradeOffersBot

**Comment by ThereWasADream** [comment]
BlueRaja, you are confused because you did not read the post.

waylaidwanderer cleared this up - this will not work. This should just be closed.
