### ISSUE TITLE
How to use SteamBot on Raspberry Pi for 24/7 use.

### ISSUE THREAD

**Issue by mx0c** [Jessecar96/SteamBot#912]
Is there anyway to start the script as service/daemon or smth else so it runs the whole time in the background?
Right now im starting the bot via ssh and: sudo mono SteamBot.exe

advanced regards

**Comment by scholtzm** [comment]
#427 #527 

Not SteamBot related.

You could use `screen` though. Look it up.

**Comment by mx0c** [comment]
Thanks alot!
