### ISSUE TITLE
Cant login after change to mobile auth

### ISSUE THREAD

**Issue by cheul123a** [Jessecar96/SteamBot#915]
![20160125_170429](https://cloud.githubusercontent.com/assets/16876596/12546957/8c126b06-c390-11e5-82c7-5efa62d39f74.jpg)

How to solve this problem help me im noob

**Comment by cheul123a** [comment]
How to link auth??

**Comment by BlueRaja** [comment]
`exec 0 linkauth`

**Comment by cheul123a** [comment]
@BuluRaja where should i text that?

**Comment by scholtzm** [comment]
This is wonderful. :grinning:

**Comment by cheul123a** [comment]
@BlueRaja where should i text that

**Comment by cheul123a** [comment]
@BlueRaja  @scholtzm  
![1453718849031](https://cloud.githubusercontent.com/assets/16876596/12548853/925f36c2-c39c-11e5-875b-bf8834e484d5.jpg)
What should i do next im noob

**Comment by scholtzm** [comment]
Reading #427 & #527 would be a good start.

**Comment by cheul123a** [comment]
I solve it thx
