### ISSUE TITLE
Bot does not start with 2fa

### ISSUE THREAD

**Issue by crEpid** [Jessecar96/SteamBot#916]
Hi, my question is as logear a bot that already have Steam Guard enabled as the 2FA not generate or recognize me the auth code you put that sends me the phone.

Apologies for the English, I use a translator
![issuebot](https://cloud.githubusercontent.com/assets/6362979/12655276/e85c94fc-c5d6-11e5-9b08-9c2d530ce5bf.png)

**Comment by BlueRaja** [comment]
https://github.com/Jessecar96/SteamBot/issues/915#issuecomment-174447134

**Comment by crEpid** [comment]
@BlueRaja check this

![issuebot2](https://cloud.githubusercontent.com/assets/6362979/12655934/275c3614-c5da-11e5-9ee9-730d80bf6ecb.png)

**Comment by BlueRaja** [comment]
Looks like a dependency issue.  Try merging PR #913 and see if that fixes it.

**Comment by crEpid** [comment]
@BlueRaja  It was a problem of versions, now I have the following problem

![issuebot3](https://cloud.githubusercontent.com/assets/6362979/12656465/30ff3f2e-c5dd-11e5-822e-58cc1977bdb1.png)

You know that is?

**Comment by BlueRaja** [comment]
That's a bug in SteamAuth, that is also fixed in #913
