### ISSUE TITLE
Bot Error

### ISSUE THREAD

**Issue by MrBrist** [Jessecar96/SteamBot#918]
I am getting this error:
https://gyazo.com/7d76188983b0b355d914aba1808381f1
Please help :)

**Comment by scholtzm** [comment]
Wrong repo.

**Comment by shloserb** [comment]
I have some problem, help me pls
![ggfek2u](https://cloud.githubusercontent.com/assets/8955974/12895632/122e3b32-cea6-11e5-9f09-5b96f3b55f51.png)

**Comment by poonkje112** [comment]
@MrBrist  this has something to do with newtonsoft.json
Follow this [video](https://www.youtube.com/watch?v=detJqxGdMfQ) to fix it.

**Comment by scholtzm** [comment]
@BlueRaja This one can be closed.
