### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by joshuabrand1** [Jessecar96/SteamBot#919]
I am trying to build the bot and I am getting the following errors:
http://postimg.org/image/i8p6s06hx/
Please Help!!

**Comment by scholtzm** [comment]
Seems like you did not clone the repo properly.

**Comment by joshuabrand1** [comment]
I have cloned it again and now have 53 errors and 8 warnings. Lots of them being 'The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)'  Project - SteamAuth 

any ideas?

**Comment by scholtzm** [comment]
Remove and add Newtonsoft.Json from SteamAuth via NuGet manager.

**Comment by BlueRaja** [comment]
#913 should fix it, try merging that PR into your repo (and please comment on the PR if it works so we can get it merged)

**Comment by joshuabrand1** [comment]
@BlueRaja I can't merge the PR as it says 'Only those with write access to this repository can merge pull requests.'

**Comment by BlueRaja** [comment]
I meant merge into your own repo...  you need to add my repo as a remote and merge that branch.  See for example [here](http://stackoverflow.com/questions/12921125/git-merge-branch-of-another-remote) or [here](http://stackoverflow.com/questions/2602546/how-do-i-git-fetch-and-git-merge-from-a-remote-tracking-branch-like-git-pu)

**Comment by joshuabrand1** [comment]
@BlueRaja sorry I am inexperienced at this and cannot figure out what you mean. I did however try the build on a different computer and the bot compiled first time with no errors.

**Comment by BlueRaja** [comment]
Fix was merged, try the latest develop and reopen issue if problem persists.
