### ISSUE TITLE
keyuserhundler some errors

### ISSUE THREAD

**Issue by Mo7TaRiF** [Jessecar96/SteamBot#920]
Hello,
Please i need some help with errors in the image if anyone could help me
![untitled](https://cloud.githubusercontent.com/assets/16272383/12803875/a2eae52a-caf6-11e5-95ba-9df03e5577f5.png)
thanks

**Comment by BlueRaja** [comment]
#427 #527

**Comment by scholtzm** [comment]
Also, there's no KeyUserHandler in SteamBot. You downloaded some bootleg code distribution.

**Comment by Mo7TaRiF** [comment]
anyway thanks for your help i hope i find the solution
Best luck for you
