### ISSUE TITLE
WARN: Disconnect from Steam...

### ISSUE THREAD

**Issue by SyfuxX** [Jessecar96/SteamBot#921]
Hello, 

First thing I say, nice bot but I have an issue with the bot.

![unbenannt](https://cloud.githubusercontent.com/assets/17093566/12865088/ece7bdd0-cca2-11e5-9761-5d4a72c9d8a9.png)

I hope you can help me fast.
I have it on my Windows, so it's the issue that I don't host it on a server or what ever because there is no tutorial how to do this.

**Comment by Jessecar96** [comment]
Error 85 is "AccountLoginDeniedNeedTwoFactor"
Looks like you setup your account wrong?
