### ISSUE TITLE
Bot issue

### ISSUE THREAD

**Issue by maitiux** [Jessecar96/SteamBot#925]
Hi, when i start the bot i get this 

C:\Users\matth\Desktop\bot>node bot1.js
C:\Users\matth\Desktop\bot\bot1.js:313
                        steam.sendMessage(steamID,'steam.sendMessage (steamID, ' Game over ! ');');
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

C:\Users\matth\Desktop\bot>pause
Press any key to continue . . .

how do i fix this problem?

**Comment by scholtzm** [comment]
Not related to SteamBot.

You might also like to learn programming first.

**Comment by maitiux** [comment]
what is it related to then? and how will i resolve it because my site is almost done just have to add in more features. I never done this with a bot before so im new, i apologize. I dont know what else to do, i just need it for depositing and withdrawing items. Im not sure what else i have to change because i linked it too the server and all. Anyways thanks for getting back to me.

**Comment by BlueRaja** [comment]
#427 #527
