### ISSUE TITLE
My bot does accept the trades, but is says that an Steam API error encountered, why?

### ISSUE THREAD

**Issue by HansenDansen** [Jessecar96/SteamBot#926]
Hello Everyone! My bot does accept the trades, but is says that an Steam API error encountered, i have typed in the API Key in the Settings.json file.. This is the settings i use, is there anything wrong with it? http://pastebin.com/pYcMpkfG A picture that shows the problem http://imgur.com/dgnzWDs I hope you guys can help! :)

**Comment by FrozenHaxor** [comment]
No part of SteamBot will ever print anything like "Steam API error encountered". Certainly not the SimpleUserHandler which you have in your settings.

You are using third party code which produces this. This error is not SteamBot related at all.

#427 #527

**Comment by HansenDansen** [comment]
My fault, i did use https://github.com/ztizzlegaming/CSGOWinBig-SteamBot but in there i cant send an Issue, can you still help me with the problem? :) :+1:

**Comment by HansenDansen** [comment]
And i did also post the issue on the SubReddit, but it got deleted due to one of the rules in there :)

**Comment by FrozenHaxor** [comment]
This is an issue tracker for the developers, not a helpdesk for third party end user code. Posting this sort of stuff here will only make people mad as most of us have email notifications about tracker activity.

**Comment by HansenDansen** [comment]
I'm sorry, i'll delete this post then..

**Comment by waylaidwanderer** [comment]
I removed your post for a reason. If it breaks a rule on /r/SteamBot, why on earth would you post it here?
