### ISSUE TITLE
Starting the Bot Fully

### ISSUE THREAD

**Issue by provok3d** [Jessecar96/SteamBot#927]
![bot](https://cloud.githubusercontent.com/assets/17495748/13352783/a91e28ea-dcca-11e5-9d83-2908205c7efc.png)

Good evening Jessecar & other Github users,

So I have downloaded the bot files and in visual basic, fixed the NuGets, and compiled the bot.
I have my settings.json file completed (I believe its correct) 

I have run exec 0 authlink and link the bot. (email and Mobile code).

What now. doesnt look like bots online??

**Comment by BlueRaja** [comment]
I think the error code is pretty self-explanatory, you need to unlink the existing mobile authenticator first.

**Comment by provok3d** [comment]
I just ran the authlink command to show i have linked it. What next?

**Comment by provok3d** [comment]
Does it have anything to do with running the bot on windows 10?? as doesnt show any errors. It succesfully loads bot, then nothing else. Isnt it ment to successfuly authenticate too?

**Comment by provok3d** [comment]
![bot](https://cloud.githubusercontent.com/assets/17495748/13422335/1a4e5308-dfcf-11e5-8194-ce9e9281f19c.png)

So redownloaded the bot, via git desktop and not the zip. Appears it progresses furture. new error attached

**Comment by provok3d** [comment]
I just can never progress past loading bot then linking authenticator?? what is ment to happen next? bot never seems to be online

**Comment by provok3d** [comment]
http://puu.sh/lKjKH.png  

Sorry to continuely post. sure its only a minor problem. Why does my bot not get past  SUCCESS: Done Loading Bot.

I just get botmgr >   

Appears from this photo should continue to do the 2fa etc and fully log on

**Comment by BlueRaja** [comment]
Please see #427.  I'm going to close this because you're spamming everyone's inboxes.
