### ISSUE TITLE
Login error(I think?)

### ISSUE THREAD

**Issue by urlingsluc** [Jessecar96/SteamBot#931]
![foutcode steambot](https://cloud.githubusercontent.com/assets/17547923/13396486/14d252d8-def5-11e5-8f7e-de36b4525346.jpg)

Hi,
I'm trying to login in the SteamBot but i always get this error. I tried to fix it by revoking the api key from my main-account and the bot-account. But that didnt work.
I would like to ask you if you know how to fix this?

Kind regards,
Luc Urlings

**Comment by provok3d** [comment]
Unable to assist you with your error unfortunately,
As I too am struggling to get my bot to work, but
Your error shows your steam api key, so prob worth , getting a new one reissued!

**Comment by urlingsluc** [comment]
ow yes indeed, thanks. I hope someone is out there who knows more about the error.

By the way "De externe server heeft een fout geretourneerd: (403)" means: "The external server returned an error: (403)"

**Comment by BlueRaja** [comment]
Are you able to access the [GetTradeOffers](https://developer.valvesoftware.com/wiki/Steam_Web_API/IEconService#GetTradeOffers_.28v1.29) API through the URL?  The only reason I can think of that this would happen is that your key _(which is shown in that image btw, you should remove it)_ is incorrect.

**Comment by urlingsluc** [comment]
I think the steam servers were down today and yesterday, because now it just works fine. I dont know what the issue was, but thanks for all your time, I really appreciate it
