### ISSUE TITLE
Bot.cs "

### ISSUE THREAD

**Issue by KennyTK** [Jessecar96/SteamBot#935]
Here is the error from visual studios 
"'ICallbackMsg' does not contain a definition for 'Handle' and no extension method 'Handle' accepting a first argument of type 'ICallbackMsg' could be found (are you missing a using directive or an assembly reference?)	ExampleBot	C:\Users\KennyThaKoala\Desktop\TradeBot\SteamBot-master\SteamBot\Bot.cs	448	Active"

I have not modified the code in any way since download other then renaming the main folder. I am absolutely stumped on what to change if 'Handle' doesn't exist as I have little understanding of the code.

**Comment by scholtzm** [comment]
You need to install correct version of SteamKit, [v1.6.2 to be precise](https://github.com/Jessecar96/SteamBot/blob/master/SteamTrade/packages.config#L6).

This is usually done automatically for you (when using Visual Studiou at least) so you must have done something wrong.

**Comment by KennyTK** [comment]
Thank you very much, problem solved. It might be worth adding the version of SteamKit required to the install guide (I don't believe it is there).
