### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ElitEXE** [Jessecar96/SteamBot#940]
Because there is no way to contact most creators of this library, I've decided to break the rules to get my message out there. So please, forgive me for opening an issue that isn't technically an issue, but just hear me on this one.
I am trying to create a Port of this to PHP, a simple self-contained script (that is actually functional and documented. Half-effort, half-functional ports to PHP already exist with no documentation) that webdevelopers can ping with data using simple javascript commands, and get data back.
I know absolutely nothing about C#, and I am having trouble back-tracking through the vast amount of files that call eachother in order to retrieve session information and send trades, invites, and chat messages.
Would anyone care to comment some of the code here and send it to me just so I dont spend a week learning and trying to understand the endless includes, jobs, handlers, and callbacks?

Again, sorry for breaking the guides/ rules but it annoys me that no real versions of this exist in PHP.

**Comment by Mick-Ashton** [comment]
And please don't link me to the javascript version of this, it is much harder to follow than the C# version. I prefer to transcribe from the roots, not another transcription

**Comment by scholtzm** [comment]
There's no SteamKit port for PHP as far as I know. Going to be a huge amount of work without it.

Also, this really does not belong here. Please respect the rules and redirect your questions to /r/SteamBot. #427

**Comment by ElitEXE** [comment]
Thank you, I was unaware of the reddit page

**Comment by waylaidwanderer** [comment]
> Half-effort, half-functional ports to PHP already exist with no documentation

If you're talking about https://github.com/waylaidwanderer/PHP-SteamCommunity, I'm insulted :(

**Comment by ElitEXE** [comment]
Lol nope. I'm talking about literally half-functional ports that still require usage of the original C# project. I think your code is very well done and put together :) Im working to create one using your code that works for webservers, since I see that yours is built for command lines. I'll also work with yours to help keep the project going, looking great so far :D

**Comment by waylaidwanderer** [comment]
Lol thanks. The code should work on webservers with minimal adjustment as well.

**Comment by ElitEXE** [comment]
And frankly I need to condense your files to save space on servers and strip out what a webserver that only sends trade offers doesn't need. Things like friends lists, groups, etc. arent needed for trades.
