### ISSUE TITLE
Connect steam guard

### ISSUE THREAD

**Issue by IvanOpenProject** [Jessecar96/SteamBot#941]
Excuse me, I could not find information on how to connect Steam Guard. Can you tell how to log in and accept the trade if I want to connect Steam Guard.

My first problem in screenshot: (email auth on account):
![image](https://cloud.githubusercontent.com/assets/14070140/13728224/e2e4553c-e921-11e5-8506-496cae2028bb.png)
password in config is true 100%, but need authcode for auth from mail

**Comment by scholtzm** [comment]
#427 #527

**Comment by IvanOpenProject** [comment]
thank you, sorry for the stupid question
