### ISSUE TITLE
Need some help for my 1st bot

### ISSUE THREAD

**Issue by jb1207** [Jessecar96/SteamBot#949]
Hi everyone and thanks for thoses who will take the time to read.
My english isnt perfect sorry about that.
So I followed the wiki to build the bot and did the basic config
So it seems to be running but when i send an offer (just for test) to give him an item, nothing happens.
Im a bit lost now and i think im missing something.
My final purpose is to set a 1:1 same card bot in the first instance.
We will see for more complicated stuff later if im able to do just simple things.

Thanks for reading and i hope your help

**Comment by BlueRaja** [comment]
#427
