### ISSUE TITLE
JSON errors when building.

### ISSUE THREAD

**Issue by thecsgobank** [Jessecar96/SteamBot#955]
This has happened to me before and I know how to fix it, I just need to change the version of Newton JSON to the right version in my package manager but does anyone know which version of JSON and steamkit I should use thanks

**Comment by RafalNiewinski** [comment]
Current version is provided with suggestion of installing this versions of NuGet packages:
```c#
<package id="Newtonsoft.Json" version="8.0.2" targetFramework="net452" />
<package id="protobuf-net" version="2.0.0.668" targetFramework="net451" />
<package id="SteamAuth" version="1.0.1" targetFramework="net452" />
<package id="SteamKit2" version="1.6.2" targetFramework="net451" />
```

but Newtonsoft.Json can be newer if exists

**Comment by BlueRaja** [comment]
I believe you're not using the latest version of the bot, this was fixed a while ago.  Please reopen if you're seeing this with a clean checkout of the repo.
