### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by DJCookiez** [Jessecar96/SteamBot#956]
I get this error when i start my bot:

[(System) 2016-03-29 18:58:56] INFO: Launching Bot CSGODice.net | BOT[1]...

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'SteamTrade, Version=0.1.0.33928, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at SteamBot.BotManager.RunningBot.SpawnBotThread(BotInfo botConfig)
   at SteamBot.BotManager.RunningBot.Start() in C:\Users\Sams-PC\Desktop\SteamBot-master\SteamBot\BotManager.cs:line 389
   at SteamBot.BotManager.StartBots() in C:\Users\Sams-PC\Desktop\SteamBot-master\SteamBot\BotManager.cs:line 89
   at SteamBot.Program.BotManagerMode() in C:\Users\Sams-PC\Desktop\SteamBot-master\SteamBot\Program.cs:line 140
   at SteamBot.Program.Main(String[] args) in C:\Users\Sams-PC\Desktop\SteamBot-master\SteamBot\Program.cs:line 40

Any ideas?

**Comment by scholtzm** [comment]
> Could not load file or assembly 'SteamTrade

Tells you right there.

**Comment by DJCookiez** [comment]
Yes but i do not know how to fix it.

Im not familiar with all this code

**Comment by RafalNiewinski** [comment]
This is not code related error, but standard situation when you missed to compile some of dependencies or missed to copy required .dll file with your .exe

If you are familiar with C# and .NET, it could be easy to fix.

**Comment by DJCookiez** [comment]
Well im learning c# at the moment so no, and when i compiled it there were no errors:

Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Build started: Project: SteamTrade, Configuration: Debug Any CPU ------
1>  Restoring NuGet packages...
1>  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
1>  All packages listed in packages.config are already installed.
1>  SteamTrade -> C:\Users\Sams-PC\Desktop\SteamBot-master\SteamTrade\bin\Debug\SteamTrade.dll
2>------ Build started: Project: ExampleBot, Configuration: Debug Any CPU ------
2>  Restoring NuGet packages...
2>  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
2>  All packages listed in packages.config are already installed.
2>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "MonoDevelop.CSharpBinding, Version=2.6.0.0, Culture=neutral". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Users\Sams-PC\Desktop\SteamBot-master\SteamBot\Bot.cs(1056,17,1056,20): warning CS0618: 'Bot.log' is obsolete: 'Refactored to be Log instead of log'
2>  ExampleBot -> C:\Users\Sams-PC\Desktop\SteamBot-master\Bin\Debug\SteamBot.exe
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by scholtzm** [comment]
Looks like your A/V is killing the `SteamTrade.dll`. Try to add an exception.

Also, #427.

**Comment by DJCookiez** [comment]
Would you be able to help me with this as i am not experienced with this

**Comment by DJCookiez** [comment]
https://youtu.be/X9c7mMUdArM

This is me compiling it again but getting the same error.

**Comment by RafalNiewinski** [comment]
Do not click "Clean PC" in your Windows Deffender. You should select "Show details" and add detected files to trust zone.

**Comment by DJCookiez** [comment]
So how would i set it up? is it automatic when i input it for the first time?

**Comment by BlueRaja** [comment]
Please take this to Reddit, as mentioned in #427. You are spamming everyone's emails by discussing this on the issue-tracker.
