### ISSUE TITLE
Fast incoming trade offers don't get served and disappear.

### ISSUE THREAD

**Issue by sqruf** [Jessecar96/SteamBot#961]
I was playing around with SteamBot when i encountered this bug.
When i send 5 consecutive trade offers from my account to Bot's account as fast as i can, every time either one or two offers don't get served. The funny thing is that the offers are still active on my account and are awaiting acceptance. But when i log to Bot's account from a browser, there are no active trades. I downloaded a fresh copy of SteamBot, just to be sure that it isn't a problem with my custom code and the bug still occurs.
 - If i do it when Bot isn't running, they all arrive as normal.
 - If i send another trade offer to the Bot, the stuck one(s) get somehow unstuck and are then sent as normal and notifications appear.
 - If i send the offers more slowly one after another, everything goes smooth.
 - It seems that it only happens when the Bot is going to accept these offers. If they are to be declined, there is no problem

Hope it only happens when offers are sent from the same user, i can't really test it with multiple users.

Regards

**Comment by scholtzm** [comment]
This is a Steam bug.

I ran into this issue over 7 months ago: https://gist.github.com/scholtzm/8af1cc037caede283a1c
