### ISSUE TITLE
Doesn't remember SteamGUARD.

### ISSUE THREAD

**Issue by Sadusko** [Jessecar96/SteamBot#962]
My bot seems not to be remembering that this machine had logged in already once. So I have to enter the steamguard code every single time.

**Comment by Sadusko** [comment]
My issue hasn't been solved yet you close it? Maybe give some information.

**Comment by RafalNiewinski** [comment]
It's not a bug, it is a feature.
CLOSED PERMANENTLY

**Comment by Sadusko** [comment]
Actually, might be useful to help me with it instead of giving no information.

I never said that it was a bug by the way because I know its possible and its functionaling but I don't know how.

**Comment by scholtzm** [comment]
If you are using 2FA, then yes, you will need to enter the code every single time unless you setup your bot to generate the code on its own.

**Comment by Sadusko** [comment]
I use sentry.bin

**Comment by scholtzm** [comment]
Sentry file is ignored if you have mobile SteamGuard enabled.

**Comment by waylaidwanderer** [comment]
Also, SteamBot doesn't use `sentry.bin`...

**Comment by Sadusko** [comment]
I have e-mail SteamGuard :p
