### ISSUE TITLE
Bad SMS code

### ISSUE THREAD

**Issue by GreenSlacer** [Jessecar96/SteamBot#964]
when doing 
input 0 "SMSCode"
It says the SMScode is wrong while it isnt I checked everything and it was the same one it sented me
idk whats the problem at this point

**Comment by scoliono** [comment]
Why was this closed? I have the same problem as well, but I didn't put quotes around the code.

**Comment by amkaub** [comment]
Did you resolve this i'm still getting badsms code ?

**Comment by MansourM** [comment]
I also have the same problem, I think sms thing  for steambot is broken somehow we need to use SDA  for that, im gonna try now ;)

**Comment by MansourM** [comment]
Yeah Steam desktop Authenticator worked
https://github.com/Jessecar96/SteamDesktopAuthenticator
https://github.com/Jessecar96/SteamBot/wiki/Use-an-account-from-Steam-Desktop-Authenticator
