### ISSUE TITLE
when i use keyuserhandler as botconrollclass instead of simpleuserhandle this error comes out 

### ISSUE THREAD

**Issue by DiaBlo16** [Jessecar96/SteamBot#966]
SS:https://gyazo.com/96eed29f0c3e42fda9f1915a95b35a1d

**Comment by scholtzm** [comment]
There's no "keyuserhandler" in the repo so that's probably the problem. :grinning:

**Comment by DiaBlo16** [comment]
@scholtzm please help me with the bot i can pay :(

**Comment by DiaBlo16** [comment]
@scholtzm  add me on skype:ika.diablo
steam:http://steamcommunity.com/id/james_hunter666/

**Comment by scholtzm** [comment]
#427 #527 

This is an issue tracker, not your personal helpdesk. Each one of your comments generates ~200 email notifications.

[You have been already told that once.](https://github.com/Jessecar96/SteamBot/issues/965#issuecomment-204193966)
