### ISSUE TITLE
Registering SteamBot callbacks with CalllbackManager.Subscribe()

### ISSUE THREAD

**Issue by Cristaling** [Jessecar96/SteamBot#967]
The Callback method is never fired in my case doing a simple:

`callbackManager.Subscribe<SteamNotifications.NotificationCallback>(botHandlerNotification);`

I tried using different types of notifications but no use.

**Comment by WildCard65** [comment]
Is any of the other callbacks get triggered? Do you have anything pending that can trigger the callback?

**Comment by Cristaling** [comment]
Yes, all the other callbacks are triggered and it has reasons(notifications) to get triggered.

In the end I figured it out. you have to register the Handler ("SteamNotifications" in this case) into the SteamClient instance before you use the subscribe:

`steamClient.AddHandler(new SteamNotifications());`

Then this works just fine:

`callbackManager.Subscribe<SteamNotifications.NotificationCallback>(botHandlerNotification);`

**Comment by WildCard65** [comment]
So you removed this line? https://github.com/Jessecar96/SteamBot/blob/master/SteamBot/Bot.cs#L199

**Comment by Cristaling** [comment]
I actually made my own Bot class... I have no idea how I missed that line while recoding it...

I'm sorry
