### ISSUE TITLE
 Login Error: AccountLogonDeniedNeedTwoFactorCode

### ISSUE THREAD

**Issue by ItsJD** [Jessecar96/SteamBot#972]
I built the bot, wrote the Settings.json File.
Created the authfiles Folder, extracted the zip from the SDA in there.
Than i set up my Account with it.
now when i start the Bot i get the following Error down belllow:

botmgr > botmgr > [TestBot 2016-04-05 11:21:30] ERROR: Login Error: AccountLogonDeniedNeedTwoFactorCode
[TestBot 2016-04-05 11:21:30] ERROR: Failed to generate 2FA code. Make sure you have linked the authenticator via SteamBot.

Can anyone help me Please :(
![bot error](https://cloud.githubusercontent.com/assets/18280748/14276934/2aaefa00-fb21-11e5-8654-512c1b232d65.png)

**Comment by scholtzm** [comment]
#427 #527

**Comment by ItsJD** [comment]
This Is not really helping me much :/

**Comment by BlueRaja** [comment]
Run the `exec [bot index] linkauth`.  We should probably include that in the error string.

**Comment by ItsJD** [comment]
@BlueRaja where i can find this exec ? my Folders look like this 
![bot folder 1](https://cloud.githubusercontent.com/assets/18280748/14294411/450e3302-fb71-11e5-8223-348a4462ca92.png)
![Uploading bot folder #2.png…]()
![Uploading bot folder #3.png…]()

**Comment by ItsJD** [comment]
@BlueRaja where i can find this exec ? my Folders look like this 
![bot folder 1](https://cloud.githubusercontent.com/assets/18280748/14294411/450e3302-fb71-11e5-8223-348a4462ca92.png)
![bot folder 2](https://cloud.githubusercontent.com/assets/18280748/14294414/468a65ac-fb71-11e5-9610-5212210fda37.png)
![bot folder 3](https://cloud.githubusercontent.com/assets/18280748/14294413/45d895c0-fb71-11e5-9927-42d94293cd59.png)

**Comment by BlueRaja** [comment]
It would be a command entered while running the bot.

Please continue with any further questions on the SteamBot reddit, as mentioned above.

**Comment by scholtzm** [comment]
@BlueRaja New commands should be added here: https://github.com/Jessecar96/SteamBot/wiki/Usage-Guide
