### ISSUE TITLE
crash at login

### ISSUE THREAD

**Issue by bluesksksk** [Jessecar96/SteamBot#974]
hello i filled everything in settings api key everything and when i bot 1 is logged it crash

https://ctrlv.cz/4SH7

**Comment by bluesksksk** [comment]
any help please?

**Comment by bluesksksk** [comment]
please dont close this topic

**Comment by paulo-santana** [comment]
Please, for God Sake, ask your questions at [reddit.com/r/SteamBot](http://reddit.com/r/SteamBot), stop spamming.
Read the fucking #427 & #527 topics.
