### ISSUE TITLE
i need some help

### ISSUE THREAD

**Issue by tyutyu123456** [Jessecar96/SteamBot#975]
it keeps giving me error 85/WARN: Disconnected from Steam Network! here is my config witch is literally all i have changed
{
"Admins":["76561198276075344"],
"ApiKey":"82E6F4D00DE08BC77B433D913152AC5A",
"mainLog": "syslog.log",
"UseSeparateProcesses": "false",
"AutoStartAllBots": "true",
"Bots": [
        {
            "Username":"tyutradebot",
            "Password":"mypassword",
            "ApiKey":,
            "DisplayName":"tyu-trade-bot",
            "ChatResponse":"Hi there bro",
            "logFile": "TestBot.log",
            "BotControlClass": "SteamBot.SimpleUserHandler",
            "MaximumTradeTime":180,
            "MaximumActionGap":30,
            "DisplayNamePrefix":"[AutomatedBot] ",
            "TradePollingInterval":800,
            "ConsoleLogLevel":"Success",
            "FileLogLevel":"Info",
            "AutoStart": "true",
            "SchemaLang":"en"
        }
    ]
}

**Comment by BlueRaja** [comment]
#427 #527
