### ISSUE TITLE
Trade offer problems after #934

### ISSUE THREAD

**Issue by RafalNiewinski** [Jessecar96/SteamBot#979]
Hi, I have problem with trade offers after pulling #934 changes.

My trades stopped working and I tried to debug it by adding log messages for each ```OnTradeOfferUpdated``` call.

In the results I can see that this method is always called 13 times in my case and always with the same trades.
Any new trade does not appear regardless of its status and even after bot restart.

My debug (always the same):
![debbot](https://cloud.githubusercontent.com/assets/1041387/14713756/a09a9724-07e2-11e6-8e10-076af5fce5be.PNG)

**Comment by BlueRaja** [comment]
New trade offers don't appear? o_O  Are you sure you're using the correct API key (it has to be one tied to the bot's account, not to your account)

**Comment by RafalNiewinski** [comment]
I am sure, I checked it for 2 accounts 5 minutes ago and my API key's are correct (I checked property ```Bot.ApiKey``` at breakpoint in ```OnTradeOfferUpdated```.

All working fine before I pulled latest master from github.

**Comment by RafalNiewinski** [comment]
I'm trying to investigate the problem and really there is something wrong with this merge or with my environment. 

My bot stopped working after I pulled and merged github master into my code.
Now I wanted to see if #934 really caused the problem in my case....
and
**I reversed merge commit with this pull request on my branch to make sure it is here**
and
**bot began to work again.**

It is something here or something related with this.

**Comment by RafalNiewinski** [comment]
Success, I found the problem.
It is located in this commit in tagged line: https://github.com/Jessecar96/SteamBot/commit/23b579c945195a346ed84ccbd50d92901a83ab05#diff-b5ff258942e09d2bcd91e6b6f6035e2fR56

the fifth parameter is set to ```true```,
by calling ```GetTradeOffers``` with ```historicalOnly``` set to ```true``` Steam API returns only completed offers.

**After changing this to ```false``` bot works properly.**

@BlueRaja - it is your commit so please check out Am I right in ?

**Comment by BlueRaja** [comment]
According to [the API documentation](https://developer.valvesoftware.com/wiki/Steam_Web_API/IEconService#GetTradeOffers_.28v1.29), when both `active_only` and `historical_only` are set to true, _all_ trade offers are returned.

I'll do some testing to see if the documentation is correct...

**Comment by RafalNiewinski** [comment]
I tested it today again, and when I called api with both options set to true I received 10 offers in json. When I changed ```historical_only``` to ```false``` steam returned me 11 offers with my newly created (5 minutes before) not yet processed offer.

**Comment by BlueRaja** [comment]
Fixed in #981
