### ISSUE TITLE
how to get new itemid after trade accepted?

### ISSUE THREAD

**Issue by codehehe** [Jessecar96/SteamBot#980]
except reload inventory.any ways?

**Comment by RafalNiewinski** [comment]
You can't. It can be done (like you said) by reloading your inventory and finding proper item.

**Comment by scholtzm** [comment]
You can use trade receipts, but it's not implemented in SteamBot.

**Comment by orik007** [comment]
You can start here
https://www.reddit.com/r/SteamBot/comments/3xa7yj/code_old_items_id_in_accepted_trade_offer/

**Comment by BlueRaja** [comment]
#427
