### ISSUE TITLE
Accept auto trade offers ???

### ISSUE THREAD

**Issue by TYDINC** [Jessecar96/SteamBot#986]
I want to build a gambling site. All is ready to go, but the bot is not working for withdraws.
This SteamBot work for me only, when i send him an invite to a trade through steam.

So, i press the button for withdraw and then i can set my items. I click ready and take my smartphone to accept the trade. Normally it should now deposit the items into the site and start the round.

I look into the steam account of my bot and he have a trade offer, but he do not accpet this kind of trade offer automatically.

I use the "AdminUserHandler"

Please, help me !

**Comment by aleksasavic3** [comment]
#427 #527
