### ISSUE TITLE
Removing friend make him blocked.

### ISSUE THREAD

**Issue by doktokto** [Jessecar96/SteamBot#988]
Calling ```Bot.SteamFriends.RemoveFriend(id)``` removing and blocking the user.

**Comment by BlueRaja** [comment]
I think this is a Steam bug.  I've had it happen before in Steam where if someone sends me a friend request shortly after I remove them, I never get the request.

Can you verify by going onto the page of the removed user that they are actually _blocked_?  It should say somewhere on the page, if you're logged in as the bot.

**Comment by doktokto** [comment]
Yes, I see them in blocked users list. My solution is to call right after removing ```Bot.SteamFriends.IgnoreFriend(id, false);``` but it's not good I think.

**Comment by doktokto** [comment]
Also removing not always blocking, some of removed users was not blocked. I don't know the reason.
