### ISSUE TITLE
Unable to link authenticator: BadSMSCode

### ISSUE THREAD

**Issue by checkerschaf** [Jessecar96/SteamBot#993]
Hey,

I'm using SteamBot with SteamAuth. I want to link SteamBot with my account to be able to trade. Email confirmation is working. On setting SMS-Code an error occurs: "BadSMSCode". I'm sure to type the correct code :D

Log: http://pastebin.com/uGxwZWZG

Any tips on how to fix it?

PS: My account is just 1 day old and I linken and unlinked SteamDesktopAuthenticator. Could this be an issue? If yes, can I create a new account and link it with SteamBot or are there any limitations.

Thanks for your help :)

**Comment by scholtzm** [comment]
Is your phone alreadz linked? Check here: https://store.steampowered.com/phone/manage

**Comment by checkerschaf** [comment]
Yes, my phone is linked. I already linked my account with steamdesktopautheticator, unlinked it and tried it with steambot. Not working. Double checked it with testing it with steamdesktop... and it works with it. Unlinked it again, but steambot is not working.. :(

**Comment by scholtzm** [comment]
I think @BlueRaja has experienced this issue before.

**Comment by BlueRaja** [comment]
When I had a similar issue, it turned out to be a bug with the SteamAuth, which has since been fixed.

**Comment by checkerschaf** [comment]
I already read that issue before and I already added my phone, but it does not work. Strange..

**Comment by Apostol77794** [comment]
I encountered the same problem. I have added your phone manually, but the error is still
Bot.cs
line 833: var smsCode = WaitForInput(); -->Valid code
line 834: var authResult = authLinker.FinalizeAddAuthenticator(smsCode); -->BadSMSCode

**Comment by Chrissyh93** [comment]
Hey guys i am having the same problem..is there any solution yet? >...<

**Comment by Apostol77794** [comment]
To temporarily solve the problem you can have an authentication file from your phone and add it to the folder Bin \ Debug \ authfiles

**Comment by Chrissyh93** [comment]
Hi Apostol..can u specify where to find the authentication file from my phone? im sorry i unable to find it >..<

**Comment by Apostol77794** [comment]
Hi, you can find it in File system Root(need root access)->data->data->com.valvesoftware.android.steam.community->files
name of file Steamguard-'UserId'

**Comment by Chrissyh93** [comment]
Hehhehe okay thanks man..i will try it..thank you very much =)

**Comment by chescos** [comment]
Got exactly the same issue, I can link the account with the SDA but doesn't work with Steambot, always "BadSMSCode". Anyone got a solution for this?

**Comment by chescos** [comment]
Also tried to copy the .maFile from the SDA to /authfiles/ in Bin/Debug/ but doesn't work either, suggests I haven't linked it with Steambot (I didn't but this is described in the git wiki).
Anyone?

**Comment by checkerschaf** [comment]
Oops, already fixed it a week ago. Anyway, thanks for your help :)

**Comment by chescos** [comment]
May I ask how you fixed it?

**Comment by checkerschaf** [comment]
Sure, I used the SteamAuth example and modified a bit for my purpose. This creates the required authfiles (.maFile). Then you have to copy/paste it into the authfiles directory of SteamBot and rename it to xyz.auth - done^^

**Comment by sitcom555** [comment]
still can`t slove the problem, dunno how to use SteamAuth example, copying file from phone doesn`t work ;C
