### ISSUE TITLE
How to add new code (I'm new here!)

### ISSUE THREAD

**Issue by SirAeonJay** [Jessecar96/SteamBot#994]
Basically I wanna buy summer shades item for a set price of 15.33. I can't always be around and don't have enough time to learn this c#/ I understand that i need to work out the value in scrap but how much of these codes and files do i need... I just want it to do one thing and that's buy!
If somebody could please pm me and guide me through this it would be great! thanks!

**Comment by scholtzm** [comment]
#427 #527

**Comment by SirAeonJay** [comment]
Thankyou
