### ISSUE TITLE
Virus?!

### ISSUE THREAD

**Issue by AzaPattaz** [Jessecar96/SteamBot#996]
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3026: Could not copy "obj\Debug\SteamTrade.dll" to "bin\Debug\SteamTrade.dll". Beginning retry 2 in 1000ms. Operation did not complete successfully because the file contains a virus or potentially unwanted software.
 (MSB3026) (SteamTrade)

**Comment by Bottswana** [comment]
Parts of the library were used in some malware a long time ago so SteamBot
can trigger false positives in some signature based antivirus.

Youll need to whitelist it.

**Comment by BlueRaja** [comment]
Please search the issues, this has been brought up dozens of times before.  It's a false-positive.
