### ISSUE TITLE
Problem with "mono SteamBot.exe"

### ISSUE THREAD

**Issue by nfs6661** [Jessecar96/SteamBot#998]
Hi ! I have this problem.I don't know where is error.How to fix this error ? Thank you for help ....

@ubuntu:~# mono SteamBot.exe
Runtime critical type System.RuntimeType not found

Native stacktrace:

        mono() [0x4affb8]
        /lib/x86_64-linux-gnu/libpthread.so.0(+0x10330) [0x7fec3b56e330]
        /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37) [0x7fec3afb9c37]
        /lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x7fec3afbd028]
        mono() [0x654d4f]
        mono() [0x654b3c]
        mono() [0x654bf2]
        mono() [0x5346cf]
        mono() [0x5b7c89]
        mono() [0x4273c6]
        mono(mono_main+0x393) [0x4810d3]
        mono() [0x420735]
        /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7fec3afa4f45]
        mono() [0x420ac7]

Debug info from gdb:

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

Aborted (core dumped)

**Comment by scholtzm** [comment]
#427 #527

**Comment by Psype** [comment]
Hey there ;)

... yea, closed, but what was the trick to make it work ? 
Like, the solution.

Cheers
